### ISSUE TITLE
colcon.pkg setting is ignored during binary build

### ISSUE THREAD

**Issue by wep21** [ros-infrastructure/ros_buildfarm#1009]
https://build.ros2.org/job/Rbin_uJ64__ecal__ubuntu_jammy_amd64__binary/lastBuild/console is failed, while https://build.ros2.org/job/Rsrc_uJ__ecal__ubuntu_jammy__source/lastBuild/console is succeeded.
I guess colcon.pkg setting is ignored from error message.

**Comment by cottsay** [comment]
The debian and RPM package builds do not use colcon at all. Building system packages like this is expressly not a goal for the colcon project.

You will need to patch the debian and RPM branches appropriately in the release repository for your package to inject the CMake definitions you desire.

**Comment by wep21** [comment]
@cottsay Thank you for your advice. I appreciate it if you could show the example commit to patch the debian and RPM branches.

**Comment by wep21** [comment]
@cottsay I found out [the documen](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty)t which shows how to add patches. Thank you.
