### ISSUE TITLE
ROS 2 Doc is currently broken

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#1029]
I've gotten everything back to green on CI in https://github.com/ros-infrastructure/ros_buildfarm/pull/1015 except ROS 2 Doc

The error is related to the python build process and needs to be resolved. 

https://github.com/ros-infrastructure/ros_buildfarm/pull/1015#issuecomment-1874653709

**Comment by nuclearsandwich** [comment]
This is fixed by #1031.
