### ISSUE TITLE
Requirements for jobs to run

### ISSUE THREAD

**Issue by asmodehn** [ros-infrastructure/ros_buildfarm#103]
I followed https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/environment.rst to setup a virtual environment for python3 and generated my jobs from there.

However when starting jenkins ( as a service on my OS ) it is not using that virtual environment. So when the job are using ros_buildfarm scripts ( from their own clone ), I am missing dependencies.

How is it supposed to work ?
What would be the best way to solve this problem ?
* modify the jobs to activate virtualenv when needed ( but how to do this during generation )
* launch jenkins from inside the virtualenv ( not sure if it will work... )
* give up on virtualenv and install all ros_buildfarm dependencies my system

**Comment by tfoote** [comment]
your problem is in #101 that the repo was not being checked out by the job, because the master did not have the git scm plugin. And without the repo the script is definitely not going to exist.

**Comment by asmodehn** [comment]
This is the next problem after solving #101 : 
```
11:35:02 # BEGIN SECTION: Generate Dockerfile - rosdistro cache
11:35:02 + export PYTHONPATH=/var/lib/jenkins/workspace/indigo_rosdistro-cache/ros_buildfarm:
11:35:02 + python3 -u /var/lib/jenkins/workspace/indigo_rosdistro-cache/ros_buildfarm/scripts/misc/run_rosdistro_cache_job.py --rosdistro-index-url file:///home/alexv/Projects/rosdistro-yujin/index.yaml indigo --distribution-repository-urls http://asmodehn/ubuntu/building --distribution-repository-key-files /var/lib/jenkins/workspace/indigo_rosdistro-cache/keys/0.key --dockerfile-dir /var/lib/jenkins/workspace/indigo_rosdistro-cache/docker_generate_rosdistro_cache
11:35:02 Traceback (most recent call last):
11:35:02   File "/var/lib/jenkins/workspace/indigo_rosdistro-cache/ros_buildfarm/scripts/misc/run_rosdistro_cache_job.py", line 15, in <module>
11:35:02     from ros_buildfarm.templates import create_dockerfile
11:35:02   File "/var/lib/jenkins/workspace/indigo_rosdistro-cache/ros_buildfarm/ros_buildfarm/templates/__init__.py", line 3, in <module>
11:35:02     from em import Interpreter
11:35:02 ImportError: No module named 'em'
```

**Comment by tfoote** [comment]
The virtualenv you are running is completely separate from the buildfarm. It can be run from any machine. I regularly from my laptop. 

You're missing empy installed on the master. Which is again a symptom of puppet not completing successfully as diagnosted in #101. empy should be installed on all your systems. [config here](https://github.com/ros-infrastructure/buildfarm_deployment/blob/master/master/manifests/site.pp#L303)
