### ISSUE TITLE
system failure to catch and retry

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#110]
Docker failed to destroy the container at the end which failed this job: http://54.183.26.131:8080/job/Isrc_uS__agvs_common__ubuntu_saucy__source/1/

```
# END SUBSECTION
time="2015-10-18T00:55:25Z" level=fatal msg="Error response from daemon: Cannot destroy container 8a8328a91295d3f8dc8abd2bf39cc57125d93cdeb8da690ef2771643803c8e7f: Driver aufs failed to remove root filesystem 8a8328a91295d3f8dc8abd2bf39cc57125d93cdeb8da690ef2771643803c8e7f: rename /var/lib/docker/aufs/mnt/8a8328a91295d3f8dc8abd2bf39cc57125d93cdeb8da690ef2771643803c8e7f /var/lib/docker/aufs/mnt/8a8328a91295d3f8dc8abd2bf39cc57125d93cdeb8da690ef2771643803c8e7f-removing: device or resource busy"
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
[description-setter] Could not determine description.
```

**Comment by dirk-thomas** [comment]
Before considering to workaround the problem the question is why does the docker command fail in the first place. Are other jobs using the same container name?

**Comment by dirk-thomas** [comment]
The job also uses an old version of Docker which is not representative for a new deployment.

**Comment by tfoote** [comment]
Looks to be fixed in https://github.com/ros-infrastructure/buildfarm_deployment/pull/74
