### ISSUE TITLE
blacklisting packages on a specific platform overmatches and disables sourcedebs

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#113]
Even if the sourcedeb has other binary jobs associated with it it's being disabled. 

I think this will be a race condition as to whether the blacklisted arches or the non-blacklisted arches have run more recently. 

http://54.183.26.131:8080/view/Ibin_uT64/job/Isrc_uT__qglv_opengl__ubuntu_trusty__source/

![sourcedeb_overmatching_blacklist](https://cloud.githubusercontent.com/assets/447804/10781742/27e537aa-7d07-11e5-8f75-72860c99db58.png)

**Comment by dirk-thomas** [comment]
This will be conceptionally difficult if separate build files share the same sourcedeb job. Currently a user can configure only a single build file which needs to continue to work.

**Comment by tfoote** [comment]
The root file will need to pass siblings build configuration scripts a list of it's siblings to allow them to be aware of them and not disable the shared sourcedeb jobs.

**Comment by tfoote** [comment]
@dirk-thomas can you take care of this before the end of the week?

**Comment by dirk-thomas** [comment]
I have created a patch for this in #122. @tfoote Please try this on the test build farm and confirm that it doesn't disable sourcedeb jobs from one build file which are necessary for another build file.
