### ISSUE TITLE
binarydeb job pulls wrong sourcedeb from repo if more than one is available

### ISSUE THREAD

**Issue by jjekircp** [ros-infrastructure/ros_buildfarm#114]
If the release build file includes more than one apt repository, and there is more than one sourcedeb available for a given binarydeb job, the binarydeb job will blindly take the highest version and not the one in the rosdistro.

I'm not sure if I'm running a supported configuration or not, but in my `distribution.yaml` I have my private packages alone, while retrieving all public packages directly from packages.ros.org. I have a package where I'm trying to build an older version than is currently in the indigo distribution, and its binarydeb job fails because the apt-get source command pulls the latest version available, which ends up not matching the job configuration.

I've worked around it with the following change, which obtains the version number from the rosdistro, runs apt-cache to determine the Debian package version number which matches, and then calls apt-get source with an exact version number specification.

Please take a look at the following commit and let me know if I'm misusing the custom rosdistro functionality or if I have something that I should submit for review.

https://github.com/clearpathrobotics/ros_buildfarm/commit/6e974bba01b1be39bd8850788cb8ac11a528d415

Quick detailed summary of changes:

* In scripts/release/get_sourcedeb.py I pass the rosdistro index URL into the get_sourcedeb function.
* In ros_buildfarm/templates/release/binarydeb_create_task.Dockerfile.em I pass the rosdistro index URL into get_sourcedeb.py.
* In binarydeb_job.py get_sourcedeb() I get the rosdistro index and distribution file and pull out the version corresponding to the package_name passed into the function, then call `apt-get showsrc` to find the corresponding Debian version, then change the `apt-get source` call to `package=version` instead of just `package`.

**Comment by tfoote** [comment]
In general this is something that debian packaging does not support/recommend rolling old versions of packages. Typically when you want to build an older version for distribution you do something like FAKE-NEW-VERSION_OLD-VERSION-NUMBER which will sort correctly.  This might be something reasonable but I'll have to do some whiteboarding to review.

**Comment by dirk-thomas** [comment]
I have implemented a modified version in #169. Can you please try if it works for your use case and comment here.

**Comment by jjekircp** [comment]
@dirk-thomas: Reading the diff of #169 it looks like the exact same effect as the change I made, so I can't see it not working. 
Apologies, there's a caveat to this change I've noticed after running a buildfarm with it for a while, so I'll describe it here in case you haven't run across it. Depending on which packages people add to the buildfarm and when, you can get job failures under the following circumstances:
* User bumps package X in the rosdistro
* Buildfarm begins building package X which has a downstream package Y
* User bumps package Y in the rosdistro. The Irel-trigger_jobs job does not run right away
* Buildfarm finishes building package X (Ibin_X) and triggers Ibin_Y
* The Ibin_Y job begins and looks for the sourcedeb corresponding to the rosdistro version. It's not present because the Isrc_Y job hasn't run after the rosdistro commit went in, so the Ibin_Y job fails

Normally this works fine: the Ibin_Y job builds the old version of the package, and then when Irel-trigger_jobs runs it triggers Isrc_Y and in turn Ibin_Y and the new version is built. With this change, binarydeb jobs fail if they are triggered by upstream jobs when the sourcedeb is out of date.

This has been only a minor annoyance for me so I haven't tried to fix it, but as you're maintaining a buildfarm with far more packages than mine it may be a greater concern.

**Comment by dirk-thomas** [comment]
Yes, the change is almost the same. Using the distribution cache rather then the distribution file is crucial though since GitHub might deliver an outdated file through its CDN. We had a similar problem with other job types (see #41).

Thanks for pointing out the problematic case. We thought about this case where it does generate an unwanted email but I think the value of checking for the exact version weights more. I think we should be able to improve the case in the future by doing the following: when the rosdistro cache gets generated it could immediately poke the sourcedeb jobs for packages which have changed their manifest file. That would reduce the time this race condition can happen to almost zero.
