### ISSUE TITLE
Error in sync to testing job when using package-based sync criteria

### ISSUE THREAD

**Issue by jjekircp** [ros-infrastructure/ros_buildfarm#115]
I followed the "Change the sync criteria section" in https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/configure_customized_buildfarm.rst, but got the following error when I tried to run the `Irel_sync-packages-to-testing_trusty_amd64` job:

```
# BEGIN SECTION: Run Dockerfile - check sync condition
+ rm -fr /home/jenkins-slave/workspace/Irel_sync-packages-to-testing_trusty_amd64/debian_repo_cache
+ mkdir -p /home/jenkins-slave/workspace/Irel_sync-packages-to-testing_trusty_amd64/debian_repo_cache
+ docker run --rm --cidfile=/home/jenkins-slave/workspace/Irel_sync-packages-to-testing_trusty_amd64/docker_check_sync_criteria/docker.cid -v /home/jenkins-slave/workspace/Irel_sync-packages-to-testing_trusty_amd64/ros_buildfarm:/tmp/ros_buildfarm:ro -v /home/jenkins-slave/workspace/Irel_sync-packages-to-testing_trusty_amd64/debian_repo_cache:/tmp/debian_repo_cache check_sync_condition
The following binary packages are missing to sync:
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/release/check_sync_criteria.py", line 99, in <module>
    sys.exit(main())
  File "/tmp/ros_buildfarm/scripts/release/check_sync_criteria.py", line 36, in main
    args.os_code_name, args.arch, args.cache_dir)
  File "/tmp/ros_buildfarm/scripts/release/check_sync_criteria.py", line 73, in check_sync_criteria
    for pkg_name in sorted(missing_binary_packages):
TypeError: 'int' object is not iterable
Build step 'Execute shell' marked build as failure
```
I looked at `check_sync_criteria.py` and the section from lines 65-78 (approx) which dealt with checking the list of packages specified in `sync: packages:` in the release build file against the list of packages present on the buildfarm didn't seem to make sense to me, so I updated it and now it appears to work.
Please take a look at my fix in https://github.com/clearpathrobotics/ros_buildfarm/commit/c049a1b68c790ecfda1fd3f2e3fdb416536123ca

**Comment by dirk-thomas** [comment]
I made a comment on the proposed patch: https://github.com/clearpathrobotics/ros_buildfarm/commit/c049a1b68c790ecfda1fd3f2e3fdb416536123ca#commitcomment-14165462

With that applied I think this looks good. Can you please create a PR for that?

**Comment by jjekircp** [comment]
PR https://github.com/ros-infrastructure/ros_buildfarm/pull/116 is up. Thanks for the quick response.
