### ISSUE TITLE
make default view not All

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#125]
We don't want the full list of jobs in the default page load. 

We used to use the "Manage" view, but we'd prefer to see the full build queue not the filtered queue for the "Manage" view.

**Comment by dirk-thomas** [comment]
I have already changed the setting in the running build farm. Afaik there is no API to configure that automatically. If it works fine for the next days I will add a note to the documentation.

**Comment by dirk-thomas** [comment]
I deleted the Jade devel job for rospack. Lets see if it comes back in the right view after job generation.

**Comment by dirk-thomas** [comment]
The job got regenerated in the right view.
