### ISSUE TITLE
doc jobs seem to have an old apt cache

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#134]
Now that the bootstrap phase for trusty amd64 has finished I expected the doc jobs to recover. 

However they are still failing: http://build.ros.org:8080/job/Idoc__carl_estop__ubuntu_trusty_amd64/2/console

[This line](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/scripts/doc/create_doc_task_generator.py#L452) is skipping all the ros dependencies.
```
# BEGIN SUBSECTION: overwrite CMakeLists.txt files to only generate messages
17:07:08 Generating 'CMakeLists.txt' for package 'carl_estop'
17:07:08 # END SUBSECTION
17:07:10 Always install the following generic dependencies:
17:07:10   - build-essential
17:07:10   - doxygen
17:07:10   - openssh-client
17:07:10   - python-catkin-pkg
17:07:10   - python-epydoc
17:07:10   - python-kitchen
17:07:10   - python-rospkg
17:07:10   - python-sphinx
17:07:10   - python-yaml
17:07:10   - python3
17:07:10   - python3-yaml
17:07:10   - ros-indigo-catkin
17:07:10   - ros-indigo-genmsg
17:07:10   - rsync
17:07:10 Identified the following build, run and doc dependencies (ignoring packages available from source):
17:07:10   - actionlib
17:07:10   - catkin
17:07:10   - move_base_msgs
17:07:10   - ros_ethernet_rmp
17:07:10   - roscpp
17:07:10   - std_msgs
17:07:10 Resolved the dependencies to the following binary packages:
17:07:10   - ros-indigo-actionlib
17:07:10   - ros-indigo-catkin
17:07:10   - ros-indigo-move-base-msgs
17:07:10   - ros-indigo-ros-ethernet-rmp
17:07:10   - ros-indigo-roscpp
17:07:10   - ros-indigo-std-msgs
```

Checking the repo listed it does have catkin in it. 

The last apt-get update appears to be in a cached build step
```
17:06:20 Step 15 : RUN python3 -u /tmp/wrapper_scripts/apt-get.py update-and-install -q -y git mercurial python3-apt python3-catkin-pkg python3-empy python3-rosdep python3-rosdistro subversion
17:06:27  ---> Using cache
```

There is a forced rosdep update in the same section. We should also force an apt-get update at this step
```

# BEGIN SECTION: Run Dockerfile - generating doc task
17:06:47 + rm -fr /home/jenkins-slave/workspace/Idoc__carl_estop__ubuntu_trusty_amd64/docker_doc
17:06:47 + mkdir -p /home/jenkins-slave/workspace/Idoc__carl_estop__ubuntu_trusty_amd64/docker_doc
17:06:47 + docker run --rm --cidfile=/home/jenkins-slave/workspace/Idoc__carl_estop__ubuntu_trusty_amd64/docker_generating_docker/docker.cid -e=HOME=/home/buildfarm -v /home/jenkins-slave/workspace/Idoc__carl_estop__ubuntu_trusty_amd64/ros_buildfarm:/tmp/ros_buildfarm:ro -v /home/jenkins-slave/workspace/Idoc__carl_estop__ubuntu_trusty_amd64/rosdoc_lite:/tmp/rosdoc_lite:ro -v /home/jenkins-slave/workspace/Idoc__carl_estop__ubuntu_trusty_amd64/catkin-sphinx:/tmp/catkin-sphinx:ro -v /home/jenkins-slave/workspace/Idoc__carl_estop__ubuntu_trusty_amd64/rosdoc_index:/tmp/rosdoc_index:ro -v /home/jenkins-slave/workspace/Idoc__carl_estop__ubuntu_trusty_amd64/catkin_workspace:/tmp/catkin_workspace -v /home/jenkins-slave/workspace/Idoc__carl_estop__ubuntu_trusty_amd64/generated_documentation:/tmp/generated_documentation -v /home/jenkins-slave/workspace/Idoc__carl_estop__ubuntu_trusty_amd64/docker_doc:/tmp/docker_doc doc_task_generation.indigo_carl_estop
17:07:00 reading in sources list data from /etc/ros/rosdep/sources.list.d
17:07:00 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
17:07:00 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
17:07:00 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
17:07:00 Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
17:07:00 Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
17:07:00 Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
17:07:00 Add distro "groovy"
17:07:00 Add distro "hydro"
17:07:00 Add distro "indigo"
17:07:00 Add distro "jade"
17:07:00 updated cache in /home/buildfarm/.ros/rosdep/sources.cache
17:07:01 
```

**Comment by tfoote** [comment]
@dirk-thomas could you look at this?

**Comment by dirk-thomas** [comment]
The problem is obviously docker: http://build.ros.org:8080/job/Idoc__carl_estop__ubuntu_trusty_amd64/2/console#console-section-10

```
Step 16 : RUN echo "2016-01-12 17:04:58 -0800"
 ---> Running in 2d644771d82f
2016-01-12 17:04:58 -0800
 ---> 0b96e53d267b
Removing intermediate container 2d644771d82f
Step 17 : ENV ROSDISTRO_INDEX_URL https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
 ---> Running in 9e109f73e134
 ---> 89f69407c123
Error removing intermediate container 9e109f73e134: rmdriverfs: Driver aufs failed to remove root filesystem 9e109f73e134805c928c70f9f393726d861a74f45d96e624230a954b5d44a67f: rename /var/lib/docker/aufs/mnt/9e109f73e134805c928c70f9f393726d861a74f45d96e624230a954b5d44a67f /var/lib/docker/aufs/mnt/9e109f73e134805c928c70f9f393726d861a74f45d96e624230a954b5d44a67f-removing: device or resource busy
```

**Comment by tfoote** [comment]
That's a docker intermediate container cleanup failure which might be a good reason to leave in the cleanup in https://github.com/ros-infrastructure/buildfarm_deployment/pull/80

I reran it and that didn't happen but it still failed. http://build.ros.org:8080/job/Idoc__carl_estop__ubuntu_trusty_amd64/3/console

**Comment by dirk-thomas** [comment]
The problem is *not* only the cleanup. The problem is that later the `apt` package is not found because likely one of the fs layers got lost and therefore the docker container doesn't contain everything specified in the Dockerfile. I think this is a severe Docker problem which needs to be investigated!

The repeated build fails again because it reuses the already cached but broken docker images.

**Comment by tfoote** [comment]
I'm not convinced that it lost a layer/used a wrong image. The error relates to removing the intermediate container, and does not refer to the image which was created and will be layered upon. 

I think that there's a caching issue with our code that does not trigger an apt-get update. It's only likely to be found in this boostrap case, and other corner cases like a new dependency is added before the job is rolled over to the next day timestamp. At this point the jobs are starting to pass as they have the timestamp for the day written into the dockerfile to bust the cache.

**Comment by dirk-thomas** [comment]
The problem is related to this patch: https://github.com/ros-infrastructure/ros_buildfarm/commit/0195226f66f96d9704926e1f5566e3fe9433ce29

Without being able to find and install the necessary dependencies it is almost guaranteed that the following build step will fail.

PR #134 forces an `apt-get update` (which will reduce efficiency of the job) to ensure to use the current apt state (rather then being happy with an up to one day old state).

But it will still fail if the doc job is run before the Debian package is available in the repo (for a new release). To prevent that (or more precisely fail earlier and with a more helpful message) the warnings printed in the patch above would need to be converted into fatal errors. But I am not sure why they were introduced a year ago so its hard to tell if that will break other cases.

**Comment by dirk-thomas** [comment]
I remember why we "allow" missing dependencies in doc jobs: to support generating a basic documentation for packages which depend on unreleased packages.
