### ISSUE TITLE
Error if repository name has a capital letter

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#139]
We need to develop policy on repository names

We have a job failing due to having a capital letter in the repository name `rosR`: http://build.ros.org:8080/job/Idoc__rosR_demos__ubuntu_trusty_amd64/

Should we support capital letters or call to_lower on before turning into a docker tag?

**Comment by dirk-thomas** [comment]
We should convert the repo name when it is being used as a docker tag.
