### ISSUE TITLE
Update base docker images

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#141]
We generated ubuntu images for 32bit and armhf which are now relatively older and consequently require more updating in each build. 

It would be more efficient to update the images and not have to update as much each run

Note scripts are here: https://github.com/osrf/ubuntu_32bit-docker and https://github.com/osrf/ubuntu_armhf-docker

Results are https://hub.docker.com/r/osrf/ubuntu_32bit/ and https://hub.docker.com/r/osrf/ubuntu_armhf/

**Comment by tfoote** [comment]
I've updated

osrf/ubuntu_armhf:trusty
osrf/ubuntu_32bit:trusty
osrf/ubuntu_32bit:vivid

And added 
osrf/ubuntu_arm64:trusty

**Comment by dirk-thomas** [comment]
I thought the goal was to automate the build of the image utilizing the Docker infrastructure. That also provides a guarantee how the image was build. Should that be moved to a new ticket?

**Comment by tfoote** [comment]
The official images are working toward supporting several different architectures. I don't think we will need to automate this in the future: See the first heading in the README https://github.com/docker-library/official-images

Once those are released we can just switch to use them.

**Comment by dirk-thomas** [comment]
Sounds good.
