### ISSUE TITLE
convert doc job uploads to dual push

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#150]
Having changed over to push the doc jobs to osuosl the rsync fetch takes a long time to download. (14 minutes per job for just the download, and since it's large enough we can't persist all the copies in the workspace.) 

An easy solution would be to both push to the webserver as well as push to the local repo server. Pushing is cheap the first time. And pulling from the local repo is also cheap.

**Comment by dirk-thomas** [comment]
Once doc jobs run in a very short time (when nothing has to be done) we should consider changing frequency to e.g. once every day.

**Comment by dirk-thomas** [comment]
Obsolete after #188.
