### ISSUE TITLE
Does shadow-fixed still available?

### ISSUE THREAD

**Issue by k-okada** [ros-infrastructure/ros_buildfarm#189]
Hi,

it seems we have newer version of movet (0.7.0) at 
http://build.ros.org/job/Irel_sync-packages-to-testing_trusty_amd64/32/consoleFull#console-section-8, but it is not appeared in the shadow fixed -> http://packages.ros.org/ros-shadow-fixed/ubuntu/pool/main/r/ros-indigo-moveit-ros-planning/
Do we still have "shadow-fixed" concept on new buildfirm? or we've move to different structure?

**Comment by tfoote** [comment]
As mentioned in the announcement email our sync to the external mirrors are going to be slightly slower for a little while while we transition the mirroring infrastructure. At the moment it requires manual processing.

**Comment by k-okada** [comment]
> Also for the next few sync cycles our shadow-fixed uploads will be
delayed as we move away from our previous host where we are still staging
our uploads through a manual process.

Sorry, I missed that line.


--
◉ Kei Okada

**Comment by tfoote** [comment]
FYI 0.7.0 is now in shadow fixed
