### ISSUE TITLE
armhf support

### ISSUE THREAD

**Issue by trainman419** [ros-infrastructure/ros_buildfarm#21]
Mostly to track my own progress in getting armhf support up and running.

I've had to adjust the home directory when building binary debs: https://github.com/trainman419/ros_buildfarm/commit/eb8b870c23914e6f9e673625eb45b7665f56a55b

armhf support should be as simple as using an armhf docker image with the proper qemu emulation layer: https://github.com/trainman419/ros_buildfarm/commit/aa47a93a247ca91956dab86bbb35055545abc667 , unfortunately this fails due to: https://github.com/djmaze/armhf-ubuntu-docker/issues/2

I'm going to try hacking around the qemu issue

**Comment by dirk-thomas** [comment]
I have build a custom Docker image: https://registry.hub.docker.com/u/osrf/ubuntu_armhf/

I added the `armhf` specific Docker image to the farm: 77b857308bf12406c2f7c13cbf9c12250581a86b

And created a specific build file with the packages up to `ros_tutorials`: https://github.com/ros-infrastructure/ros_buildfarm_config/commit/6211be65b7ac60b732d758758faee9fefc40f3c7

I here come the first armhf packages on the new buildfarm: http://54.183.26.131:8080/view/IrelUbuArmhf_Tarmhf/

**Comment by dirk-thomas** [comment]
Seems to build ARMhf packages just fine. Closing...
