### ISSUE TITLE
the doc_independent job does not invoke the upload target

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#218]
It uploads the rep results to the doc independent folder, instead of invoking the upload make target which puts them into the right place. 

It does the formulaic approach used for all others
```04:20:38 + rsync -e ssh -r --delete ./rep/html rosbot@ros.osuosl.org:/home/rosbot/docs/independent/api/./rep ```

But that ends up with the result at: http://docs.ros.org/independent/api/rep/html/rep-0000.html

We could leave it that way and symlink it or use apache rules to redirect the urls appropriately.

**Comment by dirk-thomas** [comment]
The new build farm specifies the upload in the ros_buildfarm_config files. I don't think it is viable to call an upload target provided by the repository being documented.

Therefore I would suggest to:
* remove the `upload` rule from the rep Makefile
* remove the files from www.ros.org
* add redirect rules to forward the previous URLS to the new location

**Comment by tfoote** [comment]
I have removed the directory on www.ros.org and simlinked a replacement to the doc independent location on the server. No need for redirect urls no need for
