### ISSUE TITLE
job configured missing upstream

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#274]
I think this is related to #242 but a new job has been created dynamically, but does not have any of it's dependencies present in the jenkins instance. 

http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__md49_base_controller__ubuntu_xenial_amd64__binary/

![missing_upstream](https://cloud.githubusercontent.com/assets/447804/14159810/028b5c28-f68d-11e5-9760-ba908f2ee1b9.png)

The raw config has the correct upstream projects:
```
<upstreamProjects>Kbin_uX64__catkin__ubuntu_xenial_amd64__binary,Kbin_uX64__geometry_msgs__ubuntu_xenial_amd64__binary,Kbin_uX64__md49_messages__ubuntu_xenial_amd64__binary,Kbin_uX64__md49_serialport__ubuntu_xenial_amd64__binary,Kbin_uX64__message_generation__ubuntu_xenial_amd64__binary,Kbin_uX64__message_runtime__ubuntu_xenial_amd64__binary,Kbin_uX64__roscpp__ubuntu_xenial_amd64__binary,Kbin_uX64__rospy__ubuntu_xenial_amd64__binary,Kbin_uX64__std_msgs__ubuntu_xenial_amd64__binary,Ksrc_uX__md49_base_controller__ubuntu_xenial__source</upstreamProjects>
```

Suggesting that it was an ordering issue on creation and if jenkins reload the project config it will work fine. Oddly though even the sourcedeb is not registered. 

The associated reconfigure job is here: http://build.ros.org/job/Krel_reconfigure-jobs/98/console 

It looks to have done this in the right order.
```
13:23:52 Creating job 'Kbin_uX32__md49_serialport__ubuntu_xenial_i386__binary'
13:23:52 Skipped job 'Ksrc_dJ__md49_base_controller__debian_jessie__source' because the config is the same
13:23:52 Creating job 'Kbin_dJ64__md49_base_controller__debian_jessie_amd64__binary'
13:23:52 Creating job 'Ksrc_uW__md49_base_controller__ubuntu_wily__source'
13:23:52 Creating job 'Kbin_uW64__md49_base_controller__ubuntu_wily_amd64__binary'
13:23:52 Creating job 'Kbin_uW32__md49_base_controller__ubuntu_wily_i386__binary'
13:23:52 Skipped job 'Ksrc_uX__md49_base_controller__ubuntu_xenial__source' because the config is the same
13:23:52 Creating job 'Kbin_uX64__md49_base_controller__ubuntu_xenial_amd64__binary'
13:23:52 Creating job 'Kbin_uX32__md49_base_controller__ubuntu_xenial_i386__binary'
13:23:52 Created 18 jobs, updated 0 jobs, skipped 13 jobs.
```

**Comment by dirk-thomas** [comment]
The jobs are already being generated in topological order. Also each job has the correct configuration. Jenkins does not update its in-memory representation correctly. We already trigger a rebuild (https://github.com/ros-infrastructure/ros_buildfarm/blob/f5f58aafde12956dcfeece7139dbefe087a19e23/ros_buildfarm/templates/snippet/reconfigure_jobs.groovy.em#L214) but that does not ensure that all dependencies are being used immediately.

Therefore I would close this as "wontfix" since there is nothing we can do about it.
