### ISSUE TITLE
jenkins.ini format

### ISSUE THREAD

**Issue by dhood** [ros-infrastructure/ros_buildfarm#275]
What is the appropriate format for `~/.buildfarm/jenkins.ini` please?

I'm out of ideas for what to try in order to flesh out the [example](https://github.com/dhood/ros_buildfarm/blob/master/doc/environment.rst#provide-credentials-for-jenkins-master).. keep getting `Could not find credentials for 'http://54.183.26.131:8080' in file '/home/dhood/.buildfarm/jenkins.ini'`. presumably my username is dhood and my password is my api token which I can get at http://build.ros.org/user/dhood/configure without issues

**Comment by tfoote** [comment]
```
[DEFAULT]
username=USERNAME
password=PASSWORD/TOKEN
```

Where DEFAULT can be the host such as http://54.183.26.131:8080 or if you're only using one DEFAULT can be left.  You can have multiple entries with different credentials for different hosts. 
USERNAME and PASSWORD/TOKEN need to be updated

We should add this to the docs. There's been others confused about this.

**Comment by dirk-thomas** [comment]
What is missing or unclear from the existing documentation: https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/environment.rst#provide-credentials-for-jenkins-master

**Comment by tfoote** [comment]
Yeah, that does give an example but doesn't explain the format. We should mention that there can be multiple entries for different hosts, and also extend it to explain which github tokens to use, and how to get them, if using github for authentication.

**Comment by dirk-thomas** [comment]
I think the `.ini` format is a standard we don't have to describe in our document. I added a link to the wikipedia page in #276.

Regarding the login: we can't assume in our documentation that Jenkins uses GitHub for login. I added a conditional note about it with a link to the GitHub help.
