### ISSUE TITLE
need a reliable way to kill jobs after timeout

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/ros_buildfarm#28]
Some jobs running for 20+ hours and not terminating:

* http://54.183.26.131:8080/view/IdevT64/job/IdevT64__laser_assembler__ubuntu_trusty_amd64/3/
* http://54.183.26.131:8080/view/IdevT64/job/IdevT64__warehouse_ros__ubuntu_trusty_amd64/2/

**Comment by dirk-thomas** [comment]
Good job to try it with is http://54.183.26.131:8080/view/Manage/job/IdevT64__warehouse_ros__ubuntu_trusty_amd64/ since it reliably hangs forever.

**Comment by dirk-thomas** [comment]
We will see if the new process reaper (#18) will help at all but I am not very optimistic...

**Comment by tfoote** [comment]
The reaper could always have an outside build limit, and tear everything down if jenkins fails to timeout.
