### ISSUE TITLE
Doc job does not warn about failing sphinx documentation.

### ISSUE THREAD

**Issue by vrabaud** [ros-infrastructure/ros_buildfarm#284]
E.g.
http://build.ros.org/view/Jdoc/job/Jdoc__vision_opencv__ubuntu_trusty_amd64/16/consoleFull
is green while the Python doc is not generated; look for:

    ERROR: no conf.py for sphinx build of [image_geometry]

And the "Look for warnings" section does not mention anything.

Maybe rosdoc_lite does not raise the proper error, not sure. I'll fix the error on my side. Thx.

**Comment by dirk-thomas** [comment]
As you already guessed the build farm has no way to notice that case, see https://github.com/ros-infrastructure/rosdoc_lite/blob/a178342e434c9147f7c21dcffdd93a245e6fca44/src/rosdoc_lite/sphinxenator.py#L78 Please open a ticket against `rosdoc_lite` instead.

**Comment by dirk-thomas** [comment]
Closing in favor of ros-infrastructure/rosdoc_lite#63
