### ISSUE TITLE
prerelease website URL confusion

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/ros_buildfarm#288]
- Seems to work http://prerelease.ros.org/jade
- Never returns http://prerelease.ros.org/create_job/jade

Same for Indigo.

I guess back in non-docker prerelease era (well not long ago) the URL formula was the latter and my browsers remember them. If we could disable those URLs that'd be ideal.

**Comment by dirk-thomas** [comment]
This might be related to ros-infrastructure/prerelease_website#23

Can you please explain where you found these links (and why you filled the ticket in this repo)?

**Comment by 130s** [comment]
Oh, nevermind. Prerelease scripts [are stored in this repo](https://github.com/ros-infrastructure/ros_buildfarm/tree/master/scripts/prerelease) so I couldn't think of https://github.com/ros-infrastructure/prerelease_website repo.
And where I got these links are explained https://github.com/ros-infrastructure/ros_buildfarm/issues/288#issue-150194522.
