### ISSUE TITLE
catkin_make_isolated not found

### ISSUE THREAD

**Issue by felixduvallet** [ros-infrastructure/ros_buildfarm#295]
I am trying to run the docker prerelease script on a new package I'm releasing ([grasp_synergy](https://github.com/felixduvallet/grasp-synergy)) and am running against a problem with the `catkin_make_isolated` step:

```
+ echo # BEGIN SECTION: Run Dockerfile - build and test
# BEGIN SECTION: Run Dockerfile - build and test
+ docker run --rm --cidfile=/home/felixd/tmp/prerelease_job/docker_overlay_build_and_test/docker.cid -v /home/felixd/tmp/prerelease_job/ros_buildfarm:/tmp/ros_buildfarm:ro -v /home/felixd/tmp/prerelease_job/catkin_workspace:/tmp/catkin_workspace:ro -v /home/felixd/tmp/prerelease_job/catkin_workspace_overlay:/tmp/catkin_workspace_overlay devel_build_and_test.indigo_prerelease_overlay
# BEGIN SUBSECTION: build workspace in isolation
Invoking 'PYTHONIOENCODING=utf_8 PYTHONUNBUFFERED=1 catkin_make_isolated --cmake-args -DCATKIN_ENABLE_TESTING=1 -DCATKIN_SKIP_TESTING=0 -DCATKIN_TEST_RESULTS_DIR=/tmp/catkin_workspace_overlay/test_results --catkin-make-args -j1' in '/tmp/catkin_workspace_overlay'
/bin/sh: 1: catkin_make_isolated: not found
# END SUBSECTION
```
Obviously I have catkin installed on my system, but the Docker image doesn't appear to be installing it.

I have successfully run the same prerelease script on an existing package without errors, but I am unable to find a meaningful difference in the package configurations to put me on the right path.

I am pretty sure this is an issue from my side, but what would cause this error: my package configuration, something else in my package, or in the buildfarm script?

**Comment by dirk-thomas** [comment]
Please add more information for others to reproduce your case. E.g. the exact commands you ran, any output why you conclude `catkin` wasn't installed within `docker`, details about your platform, what version of `ros_buildfarm` you are using, etc.

**Comment by felixduvallet** [comment]
Good call, I forgot the whole point of the buildfarm script is to enable reproducibility. doh!

The commands I am running:
```
 $ generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml   indigo default ubuntu trusty amd64   grasp-synergy   --level 1   --output-dir ./
 $ ./prerelease.sh
```

I have python-ros-buildfarm 1.1.0 installed:
```
$ dpkg -s python-ros-buildfarm
Package: python-ros-buildfarm
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 753
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Architecture: all
Version: 1.1.0-1
```

The failing Docker command (as it appears to me) is:
```
Invoking 'PYTHONIOENCODING=utf_8 PYTHONUNBUFFERED=1 catkin_make_isolated --cmake-args -DCATKIN_ENABLE_TESTING=1 -DCATKIN_SKIP_TESTING=0 -DCATKIN_TEST_RESULTS_DIR=/tmp/catkin_workspace_overlay/test_results --catkin-make-args -j1' in '/tmp/catkin_workspace_overlay'
/bin/sh: 1: catkin_make_isolated: not found
```

**Comment by dirk-thomas** [comment]
If you look at the output of the prerelease I doesn't find any packages:

> No packages found in source space: /tmp/catkin_workspace/src
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~  traversing 0 packages in topological order:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I would guess that is the source of the problem (see https://github.com/ros/rosdistro/pull/11545#issuecomment-220130193).

**Comment by dirk-thomas** [comment]
With the patch in #296 your "build" would succeed (but without building anything). I will close this for now. Please feel free to comment if it continues to not work for you.
