### ISSUE TITLE
Specify rosinstall during devel job?

### ISSUE THREAD

**Issue by davetcoleman** [ros-infrastructure/ros_buildfarm#307]
I'm [Running devel Jobs on Travis](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/devel_jobs.rst#run-the-devel-job-on-travis) using your instructions and things work great for e.g. [rviz_visual_tools](https://github.com/davetcoleman/rviz_visual_tools/blob/kinetic-devel/.travis.yml). However I'd like to also use this CI method for moveit but there does not appear to be support for rosinstall files to specify other repos that I need to build from source along with the target repo. This idea is demonstrated in [industrial_ci - Build depended packages from source](https://github.com/ros-industrial/industrial_ci#optional-build-depended-packages-from-source). An example moveit rosinstall is [here](https://github.com/ros-planning/moveit_docs/blob/jade-devel/moveit.rosinstall). Is this possible?

@130s is probably interested in this response also, per https://github.com/ros-industrial/industrial_ci/issues/68

**Comment by dirk-thomas** [comment]
A *devel* job operates on a single repository (https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/devel_jobs.rst).

It sounds like what you want is a *prerelease* job which operates on multiple repositories (https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/prerelease_jobs.rst).

**Comment by davetcoleman** [comment]
My understanding is that a pre-release test was intended to be used for testing bloom release - I'm trying to setup CI for pull requests of MoveIt!. Does the pre-release build from source all of ROS? Can you specify which repos to build from source? Note that industrial_ci [already has prerelease testing](https://github.com/ros-industrial/industrial_ci#optional-run-ros-prerelease-test) optional

**Comment by dirk-thomas** [comment]
Please read the references documentation about *prerelease* jobs. They are not coupled with bloom release in any way. For your use case it might be sufficient to specify several repository names for the *underlay* and keep the *overlay* workspace empty.

**Comment by davetcoleman** [comment]
My apologies for not reading the documentation fully. I've reviewed it and am still unsure what I should specify as the *underlay* workspace vs the *overlay* ws... In my case I just want to fully build and test all of MoveIt! everytime:

```
- git: {local-name: moveit_core, uri: 'https://github.com/ros-planning/moveit_core.git', version: jade-devel}
- git: {local-name: moveit_planners, uri: 'https://github.com/ros-planning/moveit_planners.git', version: jade-devel}
- git: {local-name: moveit_ros, uri: 'https://github.com/ros-planning/moveit_ros.git', version: jade-devel}
- git: {local-name: moveit_setup_assistant, uri: 'https://github.com/ros-planning/moveit_setup_assistant.git', version: jade-devel}
- git: {local-name: moveit_msgs, uri: 'https://github.com/ros-planning/moveit_msgs.git', version: jade-devel}
- git: {local-name: moveit_plugins, uri: 'https://github.com/ros-planning/moveit_plugins.git', version: jade-devel}
- git: {local-name: moveit_commander, uri: 'https://github.com/ros-planning/moveit_commander.git', version: indigo-devel}
- git: {local-name: moveit_resources, uri: 'https://github.com/ros-planning/moveit_resources.git', version: master}
- git: {local-name: moveit_docs, uri: 'https://github.com/ros-planning/moveit_docs.git', version: jade-devel}
```

Can I set those all as *underlay* so they are treated as devel jobs and not use any *overlay* packages?

**Comment by dirk-thomas** [comment]
Yes.

**Comment by dirk-thomas** [comment]
I will close this ticket for now as I assume you were able to use a local prerelease for your use case. Please feel free to comment and the ticket can be reopened.

**Comment by davetcoleman** [comment]
Created my own Docker -based build script for Travis:
https://github.com/ros-planning/moveit_core/issues/309
