### ISSUE TITLE
TOC macro seems to ignore distro version

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/ros_buildfarm#308]
Example
In http://wiki.ros.org/bloom/Tutorials/PrereleaseTest, TOC seems to always show the content from indigo or earlier. 
I tested using `preview` button and found when the older content is removed, preview shows the content from the latest distro tag.

**Comment by tfoote** [comment]
The TOC macros is part of the wiki could you refile this against the https://github.com/ros-infrastructure/roswiki/issues

**Comment by 130s** [comment]
What the French toast I'm doing...opened at https://github.com/ros-infrastructure/roswiki/issues/173
