### ISSUE TITLE
Pull request wiki page updated

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/ros_buildfarm#309]
I just wanted to notify admins that I added some changes in http://wiki.ros.org/buildfarm/Pull%20request%20testing (I found no one is watching the page), reflecting what I found after [this QA thread](http://answers.ros.org/question/239060/usage-of-test_commit-and-test_pull_requests-in-rosdistro-file/) with Dirk. Please add whatever corrections if needed.

**Comment by dirk-thomas** [comment]
Thank you for letting us know.
