### ISSUE TITLE
release job reconfigure fails with cryptic error in the case of circular package dependency

### ISSUE THREAD

**Issue by jjekircp** [ros-infrastructure/ros_buildfarm#312]
I just started putting together a new ros_buildfarm deployment, and was mystified when my Irel_reconfigure-jobs job run failed with the following error:

```
09:48:57   File "/tmp/ros_buildfarm/scripts/release/generate_release_jobs.py", line 33, in <module>
09:48:57     sys.exit(main())
09:48:57   File "/tmp/ros_buildfarm/scripts/release/generate_release_jobs.py", line 29, in main
09:48:57     whitelist_package_names=args.package_names)
09:48:57   File "/tmp/ros_buildfarm/ros_buildfarm/release_job.py", line 177, in configure_release_jobs
09:48:57     for pkg_name in [p.name for _, p in ordered_pkg_tuples]:
09:48:57   File "/tmp/ros_buildfarm/ros_buildfarm/release_job.py", line 177, in <listcomp>
09:48:57     for pkg_name in [p.name for _, p in ordered_pkg_tuples]:
09:48:57 AttributeError: 'str' object has no attribute 'name'
09:48:57 Build step 'Execute shell' marked build as failure
```

Please disregard the line numbers above; they correspond to my fork where I added some extra debugging prints. On ros-infrastructure/ros_buildfarm master, one should look around line 167, in particular at:

```
    ordered_pkg_tuples = topological_order_packages(pkgs)
```

I printed both `pkgs` and `ordered_pkg_tuples`: `pkgs` looked fine (dict of package names mapping to catkin_pkg package objects), but `ordered_pkg_tuples` had an odd entry at the end:

```
[None, 'package_a, package_b']
```

Names of package_a and package_b have been changed to protect the innocent.
My next stop was common.py and the `topological_order_packages` function, which relies heavily on catkin_pkg, so I turned my focus to there. 
Sure enough, in catkin_pkg topological_order.py, in the `_sort_decorated_packages` function the following note is present (regarding what the function returns):

```
    When a circle is detected, a tuple with None and a string giving a
    superset of the guilty packages.
```
I checked my sources and sure enough `package_a` declares a run depend on `package_b`, and `package_b` declares a run_depend on `package_a`.

It would be helpful if ros_buildfarm could detect this condition and abort with an error message informing the user that a cycle has been found in the dependency graph and listing the offending packages rather than crashing and failing with the errors above.

**Comment by dirk-thomas** [comment]
Thank you for reporting this.

First the public API of `catkin_pkg` should mention this. That fact that you had to look at the docblock of private functions is not good. ros-infrastructure/catkin_pkg#148 adds the information to the docblocks of the public API.

Second the build farm to check for that return value and output a better error message. Please see #313 which adds this. It would be great if you could run the modified version from that branch and report back that it provides a better error message in your case (with the circular dependency still being there).

**Comment by jjekircp** [comment]
Thanks for the quick turnaround on this issue; I really appreciate it.

Here's the relevant output of a new run of this job with #313. I see exactly the error message I expect to see:

```
# BEGIN SECTION: Run Dockerfile - reconfigure jobs
11:59:16 + docker run --rm --cidfile=/home/jenkins-slave/workspace/Irel_reconfigure-jobs/docker_generate_release_jobs/docker.cid -e=GIT_BRANCH=origin/check_circular_dep --net=host -v /home/jenkins-slave/workspace/Irel_reconfigure-jobs/ros_buildfarm:/tmp/ros_buildfarm:ro -v /home/jenkins-slave/.buildfarm:/home/buildfarm/.buildfarm:ro -v /home/jenkins-slave/workspace/Irel_reconfigure-jobs/reconfigure_jobs:/tmp/reconfigure_jobs release_reconfigure_jobs
11:59:18 The build file contains the following targets:
11:59:18   - ubuntu trusty: amd64
11:59:18 The git repository version 'check_circular_dep' is different than the Python package version '1.1.1-master'
11:59:18 You might want to update the Python package version to ensure that your forked version continues to work correctly when being used outside of a git working copy (e.g. after being installed or from a tarball)
11:59:19 Traceback (most recent call last):
11:59:19   File "/tmp/ros_buildfarm/scripts/release/generate_release_jobs.py", line 33, in <module>
11:59:19     sys.exit(main())
11:59:19   File "/tmp/ros_buildfarm/scripts/release/generate_release_jobs.py", line 29, in main
11:59:19     whitelist_package_names=args.package_names)
11:59:19   File "/tmp/ros_buildfarm/ros_buildfarm/release_job.py", line 161, in configure_release_jobs
11:59:19     ordered_pkg_tuples = topological_order_packages(pkgs)
11:59:19   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 445, in topological_order_packages
11:59:19     raise RuntimeError('Circular dependency in: %s' % pkg)
11:59:19 RuntimeError: Circular dependency in: package_a, package_b
```

**Comment by dirk-thomas** [comment]
Thanks for trying it and confirming that the patch works.
