### ISSUE TITLE
dev jobs ignoring ssh authentication

### ISSUE THREAD

**Issue by mwerlberger** [ros-infrastructure/ros_buildfarm#314]
Hi,
I try to fix some final things before finally doing a PR for making the buildfarm work with private GH repos. The src and release jobs take care of the git_ssh_credential_id (given in the buildfarm config index.yaml) and set the 'SSH Agent Credentials' in the jenkins job configuration correctly. The dev jobs on the other hand ignore the setting and one needs to manually fix every job entry. Anyone has a hint where/what to fix so that the dev jobs can be configured the same way as the other jobs?
Best,
 Manuel

**Comment by tfoote** [comment]
What setting do you need to change in the job config? The clone credentials?

They're set here: https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/snippet/scm_git.xml.em#L9-L11

It gets passed into the devel job here: https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/devel/devel_job.xml.em#L52-L57

Comparing the sourcedeb job to the devel job I think [this snippet](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/release/sourcedeb_job.xml.em#L176-L183) is missing to add the ssh-agent support for the devel job: 

```
@{
credential_ids = [credential_id]
if git_ssh_credential_id:
    credential_ids.append(git_ssh_credential_id)
}@
@(SNIPPET(
    'build-wrapper_ssh-agent',
    credential_ids=credential_ids,
))@
```

**Comment by dirk-thomas** [comment]
@tfoote Can you please propose a PR with the change you think is necessary. From the above description I don't see what you want to add where. Thanks.

**Comment by dirk-thomas** [comment]
@mwerlberger Can you please try the patch from #319 and comment here if it fixes your problem.
