### ISSUE TITLE
single slave failing numerous jobs due to running out of disk space

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/ros_buildfarm#32]
A single slave fails numerous jobs:

* http://54.183.26.131:8080/job/IrelUbu_S64__ackermann_vehicle__ubuntu_saucy_amd64__binary/3/console
* http://54.183.26.131:8080/job/IrelUbu_S64__kobuki_rviz_launchers__ubuntu_saucy_amd64__binary/2/console
* http://54.183.26.131:8080/job/IrelUbu_S64__ackermann_vehicle_description__ubuntu_saucy_amd64__binary/3/console
* http://54.183.26.131:8080/job/IrelUbu_T64__moveit_msgs__ubuntu_trusty_amd64__binary/2/console

The `ssh-agent` error message is not the only symptom for that cause.

**Comment by tfoote** [comment]
I think this should be fixed by https://github.com/ros-infrastructure/buildfarm_deployment/pull/25 just merged now. It should cleanup disk space every 6 hours.

**Comment by dirk-thomas** [comment]
Even if the cleanup makes it less likely in the case that a slave runs out of disk space the problem of failing multiple jobs will persist.

**Comment by tfoote** [comment]
Yes, it should be disabling itself before a job even fails.

**Comment by dirk-thomas** [comment]
Addressed by:

* enabling the `diskcheck` plugin to force-check the slave status on every build: ff425c619a2343ecd8ce7423ac9f4a4ab911898a

* the Groovy script to disable slaves if they are low on disk space: 849be76f4cf910d9b4f95948867589fe7656f8dd
