### ISSUE TITLE
Broken link to diffutils-1.2.1.jar

### ISSUE THREAD

**Issue by mistoll** [ros-infrastructure/ros_buildfarm#339]
There's a broken link to diffutils in [devel_reconfigure-jobs_job.xml.em, line 62](https://github.com/ros-infrastructure/ros_buildfarm/blob/2d060321bc605e27a161f6432500891a05a2c5ab/ros_buildfarm/templates/devel/devel_reconfigure-jobs_job.xml.em#L62)

The link https://java-diff-utils.googlecode.com/files/diffutils-1.2.1.jar returns 404.

**Comment by dirk-thomas** [comment]
The link works just find for me. Also all current devel jobs on build.ros.org work fine too.

**Comment by ayrton04** [comment]
Any chance it's getting cached somewhere? I am getting 404 right now.

**Comment by ayrton04** [comment]
http://404checker.com/404-checker

**Comment by tfoote** [comment]
It's still working for me too, but browsing the project website they appear to have a new canonical url: 

https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/java-diff-utils/diffutils-1.2.1.jar

This is from the download listing: https://code.google.com/archive/p/java-diff-utils/downloads

**Comment by ayrton04** [comment]
How strange! In any case, the URL you mentioned is the one I used in the [PR](https://github.com/ros-infrastructure/ros_buildfarm/pull/338/files#diff-700d880152af67624617da5655a729feR62).

**Comment by mistoll** [comment]
Could this behavior be caused by some sort of load balancing and servers which are not in sync?

Nevertheless, IMO these links are not intended to be used externally and thus can easily be changed again. It would be better to use a link, which is made for programmatic download. Maybe a maven repository? 
How about this one: http://central.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.2.1/diffutils-1.2.1.jar

**Comment by dirk-thomas** [comment]
The URL from the PR seems to be pretty "stable" when looking at the docs of google code archive: https://code.google.com/archive/schema

I have merged the PR. Thank you for reporting and patching this.
