### ISSUE TITLE
Mails about ROS infrastructure issues when building packages on the build farm

### ISSUE THREAD

**Issue by fairlight1337** [ros-infrastructure/ros_buildfarm#351]
The other day I got a mail from the build farm saying that the build of my package `nav_pcontroller` failed. The log showed that it wasn't the package, but some DNS lookup problem. Relevant excerpt:
```
Get base image name from Dockerfile 'Dockerfile': osrf/debian_arm64:jessie
Check docker base image for updates: docker pull osrf/debian_arm64:jessie
Pulling repository docker.io/osrf/debian_arm64
Get https://registry-1.docker.io/v1/repositories/osrf/debian_arm64/tags/jessie:
dial tcp: lookup registry-1.docker.io: no such host
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
[description-setter] Could not determine description.
```
A couple days later (without changing the package's code) I got a Jenkins mail that the build is back to normal.

@tfoote asked me to open a ticket about this and that infrastructure hiccups shouldn't lead to notification mails for the package maintainers.

The full Jenkins log is in a pastebin [here](http://pastebin.com/kMN8tjfH).

Thanks for looking into this.

**Comment by dirk-thomas** [comment]
Thank you for reporting this specific case. I think the general idea is covered in #119 and this can be closed as a duplicate.

**Comment by fairlight1337** [comment]
Very true, thanks for the reference.
