### ISSUE TITLE
Add Debian / Fedora builds to status page?

### ISSUE THREAD

**Issue by davetcoleman** [ros-infrastructure/ros_buildfarm#353]
Not sure where to post this simple question, but why are there not status badges for Debian / Fedora on this page: http://repositories.ros.org/status_page/ros_kinetic_default.html ?

What is Xv8 Xhf X32 on this page? http://repositories.ros.org/status_page/kinetic_default.html

Could those html pages have a link or legend added that better describes all the symbols and numbers? I've mostly figured it out, but only by guessing

**Comment by dirk-thomas** [comment]
The status pages are being generated per build file. The first one you referenced is from the default build file which only contains Wily and Xenial with amd64 (64) and i386 (32).

If you look at the [listing](http://repositories.ros.org/status_page/) you will see multiple other Kinetic related pages starting with `ros-kinetic-` with the following abbreviations as a suffix:

* `dj`: Debian Jessie
* `djv8`: Debian Jessie for armv8
* `uxhf`: Ubuntu Xenial for armhf
* `uxv8`: Ubuntu Xenial for armv8

A legend would certainly be helpful. I have to check if the verbose information are available.

The `kinetic_default` page (not `ros_kinetic_default`) shows all Debian packages (not only ROS packages but also Python packages as well as third party packages) for all the platforms support across all platforms supported by all build files. (Currently it seems that page lacks the two Debian targets.)

**Comment by dirk-thomas** [comment]
The PR #354 aims to improve the legend and column labels as well as make the title more precise. It also considered the Debian targets for the repos page.

Just to clarify: the `default` suffix of the `kinetic_default` repos status pages comes from this key (https://github.com/ros-infrastructure/ros_buildfarm_config/blob/f2b0e53dfcf7987c2917b5d474b28f262be750f8/index.yaml#L87) and not from a build file.
