### ISSUE TITLE
apt-get wrapper should not wait between apt-get update and apt-get install

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#38]
The wrapper is sleeping between the update and install on retry. This increases the window for non-atomic operations. I found this when debugging https://github.com/ros-infrastructure/buildfarm_deployment/issues/41#issuecomment-74603412 

After finishing an update it waits before running apt-get update `17:32:13 Reinvoke 'apt-get install' (9/9) after sleeping 23 seconds`

I don't think this is the fix for the linked issue, but will increase the likelyhood of each update/install working when the farm is actively turning over.

**Comment by dirk-thomas** [comment]
Does this patch address the problem? 981a4c2066145da7fe99187f3975e9584a99b984

**Comment by tfoote** [comment]
With max_tries = 1 for the install this should work.
