### ISSUE TITLE
.dsc assertion failure in create_binarydeb_task_generator.py

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/ros_buildfarm#39]
Here is the relevant output:

```
Looking for the '.dsc' file of package 'ros-jade-jskeus' with version '1.0.3-0'
Could not find the right '.dsc' file
The following '.dsc' files did not match:
 - ros-jade-jskeus_1.0.2-1trusty.dsc
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 144, in <module>
    main()
  File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 64, in main
    args.binarydeb_dir, debian_package_name, debian_package_version)
  File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 121, in get_dsc_file
    assert len(dsc_files) == 1
AssertionError
Build step 'Execute shell' marked build as failure
```

Here is the job in question:

http://54.183.26.131:8080/job/Jbin_uT64__jskeus__ubuntu_trusty_amd64__binary/5/console

**Comment by tfoote** [comment]
It seems to be looking for the wrong version. This is a build of 1.0.3 but the debchange script seems to ouput 1.0.2. 

```
# BEGIN SUBSECTION: append build timestamp 09:40:00 Invoking 'debchange -v 1.0.2-1trusty-20150221-094000-0800 -p -D trusty -u high -m Append timestamp when binarydeb was built.' in '/tmp/binarydeb/ros-jade-jskeus-1.0.2' 09:40:00 # END SUBSECTION
09:40:01 Looking for the '.dsc' file of package 'ros-jade-jskeus' with version '1.0.3-0'
```

Note this is a jsk package so it has the non-standard upstream workflow which might affect the scripts.

**Comment by dirk-thomas** [comment]
@tfoote Please do not make assumptions without any evidence.

The automatically triggered job 15 minutes later worked fine. The sourcedeb for 1.0.2 was rebuild shortly before this binary job was triggered. To me it looks like that the sourcedeb job built 1.0.2 while it should have build 1.0.3. And I would assume this is related to the fact that GitHubs CDN caches data for five minutes. So the source job likely fetched an outdated rosdistro file which is a known problem.

**Comment by dirk-thomas** [comment]
Closing in favor of #41.
