### ISSUE TITLE
New source jobs not created

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/ros_buildfarm#417]
Looks like new entries in the rosdistro file don't result in new jobs being created (http://repositories.ros.org/status_page/ros_lunar_default.html?q=RED).
I'm not sure where it came from but it seems to have appeared a few days ago. What changed on the buildfarm (that I know of) since then:
- update of all the jenkins plugins and whitelisted all groovy scripts manually
- #415 
- #416

**Comment by dirk-thomas** [comment]
The Jenkins plugins have recently been updated and the xml configuration was not updated accordingly. That is why certain plugins can't load their configuration anymore and those parts of the job are basically "ineffective".

**Comment by mikaelarguedas** [comment]
this has been closed along the merge, but it will take a day or so to reconfigure the ~30k jobs so that the buildfarm can be taken out of shutdown node
