### ISSUE TITLE
Update buildfarm deployment logic because of groovy v2 changes

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/ros_buildfarm#419]
- install diffutils from [here](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/java-diff-utils/diffutils-1.2.1.jar) to /var/lib/jenkins/plugins/groovy/WEB-INF/lib/
- create a scriptApproval.xml file (referencing all scripts and methods allowed for groovy scripts to run) in /var/lib/jenkins. Content of this file at the time of the writing is [here](https://gist.github.com/mikaelarguedas/ae45814f7053e18e33b8f38207b77d71#file-scriptapproval-xml)

**Comment by dirk-thomas** [comment]
This should be filled in https://github.com/ros-infrastructure/buildfarm_deployment

**Comment by mikaelarguedas** [comment]
done, thanks for pointing it out
