### ISSUE TITLE
Check configuration of all plugins update recently

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/ros_buildfarm#420]
https://github.com/ros-infrastructure/ros_buildfarm/pull/418 fixes the breaking issues encountered after updating groovy 2 but all the other plugins should configuration should also be checked to make sure we didn't change behavior in a more subtle way

**Comment by dirk-thomas** [comment]
@tfoote Since you deployed the recent plugin updates can you please take care of this as soon as possible?

**Comment by tfoote** [comment]
We're getting diffs on reconfigure like this: 

```
11:16:33     @@ -424,1 +424,0 @@
11:16:33     -          <triggerFromChildProjects>false</triggerFromChildProjects>
11:16:33     >>>
11:16:36 Updating job 'Kbin_uX32__pointgrey_camera_driver__ubuntu_xenial_i386__binary' [2023 / 3805]
11:16:36     <<<
11:16:36     --- current config
11:16:36     +++ new config
11:16:36     @@ -424,1 +424,0 @@
11:16:36     -          <triggerFromChildProjects>false</triggerFromChildProjects>
11:16:36     >>>
```

This field was added in February: https://github.com/jenkinsci/parameterized-trigger-plugin/commit/ea3b1437aa001ccac0fa57531f492aef41109e2c

**Comment by dirk-thomas** [comment]
Since I didn't get any reply on this I have spend the time to update all job configs: see #424.
