### ISSUE TITLE
trigger_jobs.groovy does not process all jobs

### ISSUE THREAD

**Issue by ipa-mdl** [ros-infrastructure/ros_buildfarm#426]
As seen in http://build.ros.org/job/Krel_dj_trigger-jobs/23306/console:

```
00:48:28 Triggering 9 jobs...
00:48:28 Ksrc_dJ__can_msgs__debian_jessie__source
00:48:28 Ksrc_dJ__canopen_402__debian_jessie__source
00:48:28 Ksrc_dJ__canopen_chain_node__debian_jessie__source
00:48:28 Ksrc_dJ__canopen_master__debian_jessie__source
00:48:28 Ksrc_dJ__canopen_motor_node__debian_jessie__source
00:48:28 Ksrc_dJ__ros_canopen__debian_jessie__source
00:48:28   Ksrc_dJ__ros_peerjs__debian_jessie__source (skipped disabled project)
00:48:28 Triggered 6 jobs, skipped 1 jobs.
00:48:28 Finished: SUCCESS
```

The script [jumps out of the loop if a package is disabled](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/release/trigger_jobs.groovy.em#L28).

In this case the input seemed to consist of 9 sorted entries:
```
Ksrc_dJ__can_msgs__debian_jessie__source
Ksrc_dJ__canopen_402__debian_jessie__source
Ksrc_dJ__canopen_chain_node__debian_jessie__source
Ksrc_dJ__canopen_master__debian_jessie__source
Ksrc_dJ__canopen_motor_node__debian_jessie__source
Ksrc_dJ__ros_canopen__debian_jessie__source
Ksrc_dJ__ros_peerjs__debian_jessie__source
Ksrc_dJ__socketcan_bridge__debian_jessie__source
Ksrc_dJ__socketcan_interface__debian_jessie__source
```

The `socketcan` packages got discarded because the unrelated `ros_peerjs` package is disabled.

**Comment by dirk-thomas** [comment]
Thank you for reporting this. It is a regression of #423. I removed a for loop and replaced it with a condition which changed the semantic of the inner break. Will create a fix now.

**Comment by dirk-thomas** [comment]
The latest job using #427 triggered the jobs correctly: http://build.ros.org/job/Krel_dj_trigger-jobs/23335/console
