### ISSUE TITLE
Does blocked_releases_X.html refer to more than just one previous ROS distro?

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/ros_buildfarm#428]
Does [blocked_releases_lunar.html](http://repositories.ros.org/status_page/blocked_releases_lunar.html?s=6&r=1) refer to more than just one previous ROS distro?

For `moveit`, there used to be a package listed as its blocker [household_objects_database_msgs](https://github.com/ros-interactive-manipulation/household_objects_database_msgs.git) (already released into Lunar), which turned out in the latest distro Kinetic the dependency was removed while Jade still depends on it (discussion https://github.com/ros-interactive-manipulation/household_objects_database_msgs/issues/5#issuecomment-297540170).

**Comment by dirk-thomas** [comment]
The blocked status page of Lunar only compares with the previous ROS distro Kinetic. This is also described here: https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/miscellaneous_jobs.rst#status-pages
