### ISSUE TITLE
Blocked_release page reporting inaccurate dependencies

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/ros_buildfarm#429]
I came across a few inconsistencies between what the page displays vs the actual dependencies of some repos.
The following are examples of both scenario and by no means an exhaustive list.

**Dependencies that shouldn't be listed:**
`moveit` was displaying a dependency on household_objects_database_msgs while the dependency has been removed from kinetic since 0.9.3

**Dependencies the should be listed:**
`urdf_tutorials` depends on `gazebo_ros` (in the gazebo_ros_pkgs repo) but is [marked as releasable](http://repositories.ros.org/status_page/blocked_releases_lunar.html?q=id%3D%22urdf_tutorial%22&s=6&r=1) on the blocked release page

**Comment by dirk-thomas** [comment]
I don't find the first example (`moveit`) on the [current page](http://repositories.ros.org/status_page/blocked_releases_lunar.html). Can you please clarify where you see it.

> `urdf_tutorials` depends on `gazebo_ros` ...

I assume you mean `urdf_tutorial`? The currently released version [0.2.4](https://github.com/ros/rosdistro/blob/3da049d0c90b0f263b7d3e34887826194b8ac385/kinetic/distribution.yaml#L7544) does not contain a dependency on `gazebo_ros` in its [manifest](https://github.com/ros/urdf_tutorial/blob/0.2.4/package.xml).

**Comment by mikaelarguedas** [comment]
The moveit doesn't show up on the page anymore because the dependency has been released to satisfy it. see [discussion](https://github.com/ros-interactive-manipulation/household_objects_database_msgs/issues/5) and associated prs [here](https://github.com/ros/rosdistro/pull/14647) and [here](https://github.com/ros/rosdistro/pull/14694). Currently waiting on the page to be regenerated to see if the dependency on `household_objects_database_msgs` reappears now that the lunar rosdistro entry has been removed.

for `urdf_tutorial`: my bad I must have it built from source locally so rosdep shows the dependency (and the doc job must do the same) that's why the dependency appears everywhere except on the status page.

**Comment by dirk-thomas** [comment]
The latest page lists `household_objects_database_msgs` again. But not as a dependency of `moveit`.

**Comment by mikaelarguedas** [comment]
alright, it must have been an oversight of the moveit! team then, closing this given that it works as expected.
