### ISSUE TITLE
disable internet access during the build stage

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#43]
It's best practice for building debians and launchpad already enforces it: https://answers.launchpad.net/launchpad/+question/260227

This will cause some regressions. We would need to audit that before deploying fully.

**Comment by dirk-thomas** [comment]
This might be the "right" way to do it. But I would guess that a lot of jobs for already released packages will fail. And I don't think that we should break these packages.

How would you imagine to roll out a change like this?

**Comment by tfoote** [comment]
All we have to do is pass "--net=none" to docker run. 

I agree it's too late for indigo and earlier, but I think we could make it an option on the rosdistro build file, like the default abi assumptions. 

Jade doesn't have too many packages yet and we're still in prerelease. I think it would be reasonable to try it out on jade. If a few fail file tickets against them, and otherwise make it a requirement for new releases.

**Comment by dirk-thomas** [comment]
I do see the problem that several packages won't be able to build anymore with this restriction. And for some of these the maintainers won't be willing / able to perform the necessary changes. Please bring it up in the next meeting and we make a decision if this change is desired.

**Comment by dirk-thomas** [comment]
I will close this ticket for now since there have been no further comments and since it would break existing packages imo its not feasible to roll out.
