### ISSUE TITLE
new job to enumerate repeatedly failing jobs

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/ros_buildfarm#431]
For each ROS distro there should be a job which e.g. runs nightly and outputs all jobs which have been failing for "a long time". The list should help the person in charge of a ROS distro to make an informed decision what to do about it (e.g. remove the entry from the rosdistro, rollback a recent change, etc.).

The new job type is most likely a sibling of the rosdistro cache job. It should contain a system Groovy script running within the Jenkins masters vm.

**Comment by dirk-thomas** [comment]
@j-rivero In what timeframe are you planning to work on this?

**Comment by j-rivero** [comment]
> @j-rivero In what timeframe are you planning to work on this?

depending on your urgency, probably when we have the setup for ARIAC in place and working fine (means: no this week).

**Comment by dirk-thomas** [comment]
It is not an urgent feature but we want to have it at some point. I don't mind about this week but when do you plan to work on it? E.g. in two weeks, or more likely four? Any estimate would be fine.

**Comment by j-rivero** [comment]
> It is not an urgent feature but we want to have it at some point. I don't mind about this week but when do you plan to work on it? E.g. in two weeks, or more likely four? Any estimate would be fine.

Give me three weeks or ping me if we change the priority and some point.

**Comment by mikaelarguedas** [comment]
@j-rivero Do you have an updated ETA on this ?

**Comment by j-rivero** [comment]
as soon as ARIAC and SRCsim finish, next week?

**Comment by j-rivero** [comment]
Is there anyway of testing locally what the python scripts generates as Jenkins configurations?

**Comment by dirk-thomas** [comment]
> Is there anyway of testing locally what the python scripts generates as Jenkins configurations?

For which jobs? You can run the scripts to generate the maintenance jobs without pushing them to Jenkins. For existing jobs it shows the diff. I am not sure if it shows the full xml for new jobs though (but that could be added for testing if necessary).

**Comment by j-rivero** [comment]
> For which jobs? You can run the scripts to generate the maintenance jobs without pushing them to Jenkins. For existing jobs it shows the diff. I am not sure if it shows the full xml for new jobs though (but that could be added for testing if necessary).

For example, how to check the result of running `./misc/generate_rosdistro_cache_job.py`

**Comment by dirk-thomas** [comment]
> For example, how to check the result of running `./misc/generate_rosdistro_cache_job.py`

Just run the script and it will show the diff compared to the existing job. If you want it to print the full xml you will need to add a print call somewhere in this function: https://github.com/ros-infrastructure/ros_buildfarm/blob/eb0586486f1d6c869767b17b0da12dda7f1e7b23/ros_buildfarm/jenkins.py#L179

**Comment by j-rivero** [comment]
Just calling it is returning me an error in the connection. Do I need to setup credentials? Do we have instructions about how to run these scripts?

```bash
python scripts/misc/generate_rosdistro_cache_job.py --dry-run https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/master/index.yaml indigo 
Your git workspace contains local modifications. They won't propagate to the actual jobs when not available from the git repository.
Connecting to Jenkins 'http://54.183.26.131:8080'
Could not find credential file '/home/jrivero/.buildfarm/jenkins.ini'
Traceback (most recent call last):
  File "scripts/misc/generate_rosdistro_cache_job.py", line 113, in <module>
    main()
  File "scripts/misc/generate_rosdistro_cache_job.py", line 51, in main
    jenkins = connect(config.jenkins_url)
  File "/home/jrivero/code/ros/ros_buildfarm/ros_buildfarm/jenkins.py", line 63, in connect
    jenkins = JenkinsProxy(jenkins_url, username=username, password=password)
  File "/home/jrivero/code/ros/ros_buildfarm/ros_buildfarm/jenkins.py", line 42, in __init__
    super(JenkinsProxy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkins.py", line 53, in __init__
    JenkinsBase.__init__(self, baseurl, poll=not lazy)
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 35, in __init__
    self.poll()
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 57, in poll
    data = self._poll(tree=tree)
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkins.py", line 58, in _poll
    if not tree else tree)
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/jenkinsbase.py", line 77, in get_data
    response = requester.get_url(url, params)
  File "/usr/local/lib/python2.7/dist-packages/jenkinsapi/utils/requester.py", line 104, in get_url
    return requests.get(self._update_url_scheme(url), **requestKwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='54.183.26.131', port=8080): Max retries exceeded with url: /api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f673ebb3e10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
jrivero@nium ros_buildfarm $ (master) 
```

**Comment by dirk-thomas** [comment]
You need to refer to the `production` branch of the https://github.com/ros-infrastructure/ros_buildfarm_config repo.
