### ISSUE TITLE
python3-ros-buildfarm breaks python-apt

### ISSUE THREAD

**Issue by christianrauch** [ros-infrastructure/ros_buildfarm#456]
I am not sure if this is the correct place to report this issue, but installing package `python3-ros-buildfarm` on Ubuntu (for pre-release tests) breaks python-apt.
E.g. after installation I am not able to run `update-manager` (or `ubuntu-drivers`), it quits with `AttributeError: module 'apt' has no attribute 'Cache'`. I presume this is caused by file `/usr/bin/apt.py` that gets installed with the package. Uninstalling the package resolves the error.

**Comment by tfoote** [comment]
Yes, I've seen the same issue with the python2 version. I thought that I had accidentally run puppet on my host but it's also [listed in the files](https://gist.github.com/tfoote/54c09725eb30a7a8f02c8e8877c2efd4) for `python-ros-buildfarm`

**Comment by alextoind** [comment]
I believe you fully understand the problem, but you can find more details here: https://askubuntu.com/questions/928048/software-properties-gtk-crashes-on-ubuntu-16-04-startup

At the moment I think I install/uninstall `python3-ros-buildfarm` each time I need it.

**Comment by dirk-thomas** [comment]
Thank you for reporting the problem. Since the wrapper scripts don't have to be on the path to be used by the buildfarm I have removed them from the list of installed scripts. Please see #457 for the proposed fix. It would be great if you could confirm that this solves your problem.

**Comment by alextoind** [comment]
Do I just need to launch the `setup.py`?
And, one question: after the installation from source is there a safe removal script to call or I can simply override this installation with the one provided by the linux package (and then, in case, remove it)?

**Comment by dirk-thomas** [comment]
You should install the package into a virtual environment in order to be able to clean it afterwards.

**Comment by christianrauch** [comment]
The fix works. I tested with a Ubuntu live cd and `apt.py` does not get installed.

If you want to reproduce:
I had to enforce installing to /usr by: `sudo python3 setup.py install --prefix=/usr` (and create the missing folder it is complaining about).

**Comment by dirk-thomas** [comment]
@christianrauch Thank you for trying the patch and reporting back.
