### ISSUE TITLE
git clone sometimes failes with TLS packges unexpected length, add retrigger

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#48]
From: http://54.183.26.131:8080/job/Ibin_uS64__pr2_arm_kinematics__ubuntu_saucy_amd64__binary/5/

```
# BEGIN SECTION: Clone ros_buildfarm
+ rm -fr ros_buildfarm
+ git clone --depth 1 -b master https://github.com/ros-infrastructure/ros_buildfarm.git ros_buildfarm
Cloning into 'ros_buildfarm'...
fatal: unable to access 'https://github.com/ros-infrastructure/ros_buildfarm.git/': gnutls_handshake() failed: A TLS packet with unexpected length was received.
Build step 'Execute shell' marked build as failure
```

We could add retrigger logic for this.

**Comment by tfoote** [comment]
Apparently there was a github issue at that moment. The next email is a similar error: http://54.183.26.131:8080/job/Ibin_uT32__perception_pcl__ubuntu_trusty_i386__binary/11/

```
+ git clone --depth 1 -b master https://github.com/ros-infrastructure/ros_buildfarm.git ros_buildfarm
Cloning into 'ros_buildfarm'...
fatal: unable to access 'https://github.com/ros-infrastructure/ros_buildfarm.git/': Failed to connect to github.com port 443: Connection timed out
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
```

**Comment by dirk-thomas** [comment]
I am not sure what the goal of this ticket is:
* should we retry to clone the repo or
* handle the error case more gracefully (then I would close this as a duplicate of #119)?

**Comment by tfoote** [comment]
#119 is a more generic solution. This looks like a github hiccup that is not common so the general solution is probably better.
