### ISSUE TITLE
Development jobs failing with "java.io.IOException"

### ISSUE THREAD

**Issue by kmhallen** [ros-infrastructure/ros_buildfarm#489]
http://build.ros.org/job/Idev__multisense_ros__ubuntu_trusty_amd64/233/console
http://build.ros.org/job/Idev__multisense_ros__ubuntu_trusty_amd64/221/console
http://build.ros.org/job/Idev__rbdl__ubuntu_trusty_amd64/225/
http://build.ros.org/job/Idev__rbdl__ubuntu_trusty_amd64/219/
http://build.ros.org/job/Kdev__oxford_gps_eth__ubuntu_xenial_amd64/227/console
http://build.ros.org/job/Kdev__oxford_gps_eth__ubuntu_xenial_amd64/226/console
http://build.ros.org/job/Idev__oxford_gps_eth__ubuntu_trusty_amd64/239/console
http://build.ros.org/job/Idev__oxford_gps_eth__ubuntu_trusty_amd64/224/console
http://build.ros.org/job/Idev__oxford_gps_eth__ubuntu_trusty_amd64/223/console

**Comment by nuclearsandwich** [comment]
This happens right now whenever the spot price exceeds our max, which is the current on-demand price for the buildfarm region. The workers are taken offline without regard to what they're doing. There's a surge in spot demand this month that I think we're just going to have to ride out. The jobs that fail in this manner should be automatically requeued.

**Comment by kmhallen** [comment]
Okay. I probably wouldn't have noticed if my devel jobs weren't building many times a day unnecessarily (documented in issue #488).
