### ISSUE TITLE
trigger-broken not working

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#49]
There are a lot of broken jobs due to a github glitch as well as a docker memory leak. 

But if I trigger the job it doesn't trigger anything: 
http://54.183.26.131:8080/view/Manage/job/Irel_trigger-broken-with-non-broken-upstream/57/console

```
23:59:08 Started by user Admin
23:59:08 Building on master in workspace /var/lib/jenkins/jobs/Irel_trigger-broken-with-non-broken-upstream/workspace
23:59:08 Triggering builds for the following jobs:
23:59:08 Finished: SUCCESS
```

One job I would have expected it to run is: http://54.183.26.131:8080/view/Ibin_uS32/job/Ibin_uS32__rosconsole__ubuntu_saucy_i386__binary/3/console which I triggered manually. 

![trigger_broken_w](https://cloud.githubusercontent.com/assets/447804/6863821/554726ea-d415-11e4-8b81-dd2da1c37d35.png)

**Comment by tfoote** [comment]
The jobs do not appear to be running correctly still. 
I poked it here: http://54.183.26.131:8080/view/Manage/job/Irel_trigger-broken-with-non-broken-upstream/65/consoleFull  And it output that it was triggering a lot of jobs. But a spot check of those jobs show an over match. [canopen src](http://54.183.26.131:8080/view/Ibin_uS64/job/Isrc_uS__canopen_master__ubuntu_saucy__source/) is not broken. it has one green build from a month ago. 

And it's also matching the _arm jobs like the first entry [acado](http://54.183.26.131:8080/job/Ibin_arm_uThf__acado__ubuntu_trusty_armhf__binary/)

And it's printing a lot of job names now, but doesn't actually trigger them. 

(Which is good for the moment due to the overmatching. )

**Comment by dirk-thomas** [comment]
I fixed the overmatching with the recent commit. Anyway I thought the job gets reconfigure as part of the daily reconfigure job but it actually required to run the maintenance jobs to be redeployment.
