### ISSUE TITLE
rosdistro cache is updated twice for some manifests

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#497]
![image](https://user-images.githubusercontent.com/447804/34747972-55224af6-f54f-11e7-8c09-074a7c58544d.png)
http://build.ros.org/job/kinetic_rosdistro-cache/192011/
and 
http://build.ros.org/job/kinetic_rosdistro-cache/192010/
both report pos_cov_ops changed with the same change.
Full console outputs: https://gist.github.com/tfoote/a3e35290f169ed8bb79c2dba4faaff7f

I saw this in the past too for 4 cycles: 
![image](https://user-images.githubusercontent.com/447804/34748026-8b97f82e-f54f-11e7-88e9-db70c94607ed.png)

**Comment by dirk-thomas** [comment]
@tfoote Please extract the relevant information in future tickets rather than referencing output dumps with 7k lines. Otherwise every reader has to perform the same work to get the relevant information.

Btw the correct package name to search for is `pose_cov_ops`.

**Comment by dirk-thomas** [comment]
The build 192010 contains:

```
DEBUG:rosdistro:Dropping release package XML cache for pose_cov_ops
  - fetch "pose_cov_ops"
DEBUG:rosdistro:Load package.xml file from url "https://raw.githubusercontent.com/mrpt-ros-pkg-release/pose_cov_ops-release/release/kinetic/pose_cov_ops/0.2.0-0/package.xml"
  - updated manifest of package 'pose_cov_ops' to version '0.2.0'
```

The build 192011 contains:

```
DEBUG:rosdistro:Loading package.xml for package "pose_cov_ops" from cache
  - fetch "pose_cov_ops"
  - updated manifest of package 'pose_cov_ops' to version '0.2.0'
```

Based on that the title seems to be wrong. The cache is *persisted* correctly after the first build otherwise the second build wouldn't find the package in the cache. The problem is that when loaded from the cache in the second build it is not equal to what is expected.
