### ISSUE TITLE
pr jobs: warnings about 'old data' (Jenkins 2.89.3)

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/ros_buildfarm#510]
Just reporting this, not sure whether it has actual impact on the correct functioning of the jobs/farm: (all, but I don't have that many) PR jobs are listed on the *Manage Old Data* page of my Jenkins instance.

Example of an entry under the `Unreadable Data` heading:

```
hudson.model.FreeStyleProject | Ipr__my_pkg__ubuntu_trusty_amd64 | ObjectAccessException: Could not set field class org.jenkinsci.plugins.ghprb.GhprbTrigger.latestVersion : null
```

**Comment by nuclearsandwich** [comment]
I've had several test deployments since this issue was reported and haven't seen any Old Data warnings prior to https://github.com/ros-infrastructure/buildfarm_deployment/issues/193.

**Comment by dirk-thomas** [comment]
@gavanderhoorn What version of the `ghprb` plugin are you having installed when see this?

**Comment by gavanderhoorn** [comment]
`1.39`.

**Comment by dirk-thomas** [comment]
> `1.39`

We use the same version of the plugin on ros.build.org. The current snipper sets that value to `3`: https://github.com/ros-infrastructure/ros_buildfarm/blob/3b98057cee81bbb96cd95cd05b02ccfda9dd10c7/ros_buildfarm/templates/snippet/trigger_github-pull-request-builder.xml.em#L3

Looking at one of our jobs that seems to be exactly what the `config.xml` contains:

```
<org.jenkinsci.plugins.ghprb.GhprbTrigger plugin="ghprb@1.39.0">
  <spec/>
  <latestVersion>3</latestVersion>
```

I don't see a warning in our Jenkins UI for it. (Could be related to the Jenkins version, we use 2.60.3 on that machine.) Can you check and post how this part looks like in your job config?

**Comment by dirk-thomas** [comment]
I will go ahead and close this. We are about to move to the latest LTS release so this is unlikely to be the case anymore.
