### ISSUE TITLE
doc jobs: 'api_documentation' URL hard-coded?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/ros_buildfarm#511]
I'm not entirely sure, but it appears that the URL template that is used to populate the `api_documentation` key in `manifest.yaml` is hard-coded to always point to `docs.ros.org`:

https://github.com/ros-infrastructure/ros_buildfarm/blob/0d35d14a1e332fc59d2fa4365f37fd586a9cab50/scripts/doc/create_doc_task_generator.py#L399-L400

Is this as it should be, or should this actually be based on the base URL of the farm being deployed? Could the `canonical_base_url` key in the `doc-build.yaml` file be used for that?

**Comment by dirk-thomas** [comment]
Currently the doc build file doesn't contains that information (https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/configuration_options.rst#specific-options-in-doc-build-files). It would indeed be nice to make this a configuration option.

Please consider to provide a pull request for this enhancement.

**Comment by gavanderhoorn** [comment]
Is `canonical_base_url` not usable for this? From `indigo/doc-build.yaml`:

https://github.com/ros-infrastructure/ros_buildfarm_config/blob/f7dbfa52b7b98cf64544ce1bdd5884a836a70b64/indigo/doc-build.yaml#L4-L5

**Comment by dirk-thomas** [comment]
That config value will indeed be sufficient. I didn't see it since it doesn't appear in the documentation of the available options.

**Comment by dirk-thomas** [comment]
Addressed in #517.
