### ISSUE TITLE
devel_job: Run roslint targets before tests if exist

### ISSUE THREAD

**Issue by asiron** [ros-infrastructure/ros_buildfarm#538]
Is it possible to run roslint targets before tests as part of a devel_job ?

**Comment by dirk-thomas** [comment]
The buildfarm only runs the tests declared by each package. It doesn't know anything about `roslint` and can't make assumptions if a package wants to be checked or not.

Therefore I would suggest to add the roslint check as a test to the packages you would like to be tested. That would also make sure that every developer running the tests of these packages locally gets immediate feedback if there are any roslint warnings.

**Comment by asiron** [comment]
Actually, I just got a build fail on the ros buildfarm due to a linter error. I wasn't aware that the buildfarm runs roslint targets, until I added my package to a new distro (`lunar`, previously only `indigo`), which had a different roslint version for which I didnt test before locally.
