### ISSUE TITLE
race condition with binary jobs and changes in rosdistro

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/ros_buildfarm#54]
If a binary job is triggered during the time between a change to the rosdistro and the up-to 15 minutes before that same change triggers a new source deb build, then the binary job will get an error like this:

```
Looking for the '.dsc' file of package 'ros-jade-xmlrpcpp' with version '1.11.11-0'
Could not find the right '.dsc' file
The following '.dsc' files did not match:
 - ros-jade-xmlrpcpp_1.11.10-0vivid.dsc
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 144, in <module>
    main()
  File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 64, in main
    args.binarydeb_dir, debian_package_name, debian_package_version)
  File "/tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py", line 121, in get_dsc_file
    assert len(dsc_files) == 1
AssertionError
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
[description-setter] Could not determine description.
```

There are two paths to fixing this that I can see:

1. Make periodic tasks more consistent.
 - Make sure the generation of the cache and the triggering of new jobs happen at the same time.
 - Make sure that all jobs use information from the cache and not from GitHub.
2. Make periodic jobs happen based on an "on commit" hook rather than a timer.
 - Like option 1, you'll want all jobs to use the cache's information rather than GitHub's raw data.

**Comment by wjwwood** [comment]
As @dirk-thomas pointed out, if a build farm is using a cache from another farm, this race condition will always exist. So we should at least detect the error and print a more helpful message, letting normal users know that they can ignore this unless it persists. It does not make sense to re-trigger anything as far as I can tell.

**Comment by jack-oquin** [comment]
Is this why most of the e-mail I get complaining about build farm failures are transitory problems that eventually go away? I have learned to ignore them, but they still annoy.

**Comment by dirk-thomas** [comment]
@jack-oquin This ticket is about the new Docker-based build farm. It is not related to the "old" build farm on jenkins.ros.org. The new test farm does currently not notify the maintainers at all.

Similar problems exist on the old farm and the new farm addresses some of them. This is a case which would still notify maintainers but will "fix itself" with the next build already being scheduled. Until the new build farm gets deployed we will likely be able to fix this specific problem.

**Comment by jack-oquin** [comment]
OK, thanks

**Comment by dirk-thomas** [comment]
For a complete fix preventing the job to fail in the case of this race condition the sourcedeb jobs would need to be triggered immediately when a rosdistro PR is being merged. Since we currently don't have that ability the improved error message is "the best" we can do for now.

**Comment by dirk-thomas** [comment]
We still can't trigger the source jobs when changes to rosdistro are being merged but we have improved the behavior of the jobs by now: #138 #140 #157 #159
