### ISSUE TITLE
ROS Lunar pkgs appear in http://repositories.ros.org/status_page/melodic_default.html

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/ros_buildfarm#546]
Not sure if this is the right repo, but I see `ros-lunar-*` in http://repositories.ros.org/status_page/melodic_default.html, in addition to `ros-melodic-*`. 
![screenshot from 2018-05-23 12-41-55](https://user-images.githubusercontent.com/1840401/40447229-b9a8e142-5e86-11e8-90a5-22db39dd8438.png)

**Comment by mikaelarguedas** [comment]
The status page `melodic_default` shows the all the packages hosted in the ROS repositories for the platforms targeted by melodic (Arful, Bionic and Stretch).

As melodic and lunar share a common platform (Debian Stretch) it is expected that the lunar packages show up there.

If you want to see only the released ROS melodic packages you should use the `ros_melodic_default` status page: http://repositories.ros.org/status_page/ros_melodic_default.html

HTH

**Comment by 130s** [comment]
Good to know.

Sounds like this isn't an issue for you then. Thanks.
