### ISSUE TITLE
*_trigger-jobs should timeout

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#55]
There's one stuck in the docker checkout 3 hours in. http://54.183.26.131:8080/job/Jrel_trigger-jobs/6935/

We should make sure they have a timeout since it blocks the executor. The average execution time is under 30 seconds (triggering 48 packages), though it will take longer if there are more packages to trigger. During a rebuild or on indigo. But a 15 minute one should be plenty. 

```
# BEGIN SECTION: Build Dockerfile - reconfigure jobs
14:49:43 + cd /home/jenkins-slave/workspace/Jrel_trigger-jobs/docker_trigger_jobs
14:49:43 + python3 -u /home/jenkins-slave/workspace/Jrel_trigger-jobs/ros_buildfarm/scripts/misc/docker_pull_baseimage.py
14:49:43 Get base image name from Dockerfile 'Dockerfile': ubuntu:trusty
14:49:43 Check docker base image for updates: docker pull ubuntu:trusty
14:49:43 Pulling repository ubuntu
14:49:50 b7cf8f0d9e82: Pulling image (trusty) from ubuntu
14:49:50 b7cf8f0d9e82: Pulling image (trusty) from ubuntu, endpoint: https://registry-1.docker.io/v1/
14:49:50 b7cf8f0d9e82: Pulling dependent layers
14:49:50 706766fe1019: Download complete
14:49:50 a62a42e77c9c: Download complete
14:49:50 2c014f14d3d9: Download complete
14:49:50 b7cf8f0d9e82: Download complete
17:46:16 Build was aborted
17:46:16 Aborted by Admin
17:46:16 Finished: ABORTED
```

**Comment by dirk-thomas** [comment]
While adding a timeout to these jobs is straight forward I would rather not do it. We can hardly protect us against these docker failures. The same would apply to many more job types  - most of them where we don't even know a reasonable upper boundary for the timeout.

**Comment by dirk-thomas** [comment]
I will close this ticket for now since there are no further comments.
