### ISSUE TITLE
Ibin_uT32 and Ibin_arm_uThf jobs failing to install python3-catkin-pkg-modules

### ISSUE THREAD

**Issue by kmhallen** [ros-infrastructure/ros_buildfarm#559]
This issue appears to have started around 07/27/2018

Ibin_uT32:
- http://build.ros.org/view/Ibin_uT32/job/Ibin_uT32__dataspeed_pds_msgs__ubuntu_trusty_i386__binary/
- http://build.ros.org/view/Ibin_uT32/job/Ibin_uT32__image_view2__ubuntu_trusty_i386__binary/
- http://build.ros.org/view/Ibin_uT32/job/Ibin_uT32__pybind11_catkin__ubuntu_trusty_i386__binary/

Ibin_arm_uThf:
- http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__dataspeed_pds_msgs__ubuntu_trusty_armhf__binary/
- http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__image_view2__ubuntu_trusty_armhf__binary/
- http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_arm_uThf__pybind11_catkin__ubuntu_trusty_armhf__binary/

**Comment by tfoote** [comment]
This is correlated with the release of 0.4.4 and 0.4.5 of catkin_pkg It appears there's an underlying error here. All of the examples fail with 0.4.5 but that came out almost immediately after 0.4.4

```
23:14:45 dpkg-deb: error: archive '/var/cache/apt/archives/python3-catkin-pkg-modules_0.4.5-1_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
23:14:45 dpkg: error processing archive /var/cache/apt/archives/python3-catkin-pkg-modules_0.4.5-1_all.deb (--unpack):
23:14:45  subprocess dpkg-deb --control returned error exit status 2
```

A little more debugging indicates that this is not ros_buildfarm related but purely a catkin_pkg installation issue. It errors on an install in a clean docker container: https://gist.github.com/tfoote/5d8c0fd497d2dbbdee19c26d083e11e1

Refiled at: https://github.com/ros-infrastructure/catkin_pkg/issues/227
