### ISSUE TITLE
docker times out waiting for other docker images to finish download

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/ros_buildfarm#56]
Occasionally I see:

http://54.183.26.131:8080/job/Jbin_uT64__calibration_setup_helper__ubuntu_trusty_amd64__binary/10/
```
USER buildfarm
  ENTRYPOINT ["sh", "-c"]
  CMD ["PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH python3 -u /tmp/ros_buildfarm/scripts/release/get_sourcedeb.py jade calibration_setup_helper --sourcedeb-dir /tmp/binarydeb && PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH python3 -u /tmp/ros_buildfarm/scripts/release/append_build_timestamp.py jade calibration_setup_helper --sourcedeb-dir /tmp/binarydeb && PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH python3 -u /tmp/ros_buildfarm/scripts/release/create_binarydeb_task_generator.py --rosdistro-index-url https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml jade calibration_setup_helper ubuntu trusty amd64 --distribution-repository-urls http://54.183.65.232/ubuntu/building --distribution-repository-key-files /tmp/keys/0.key --binarydeb-dir /tmp/binarydeb --dockerfile-dir /tmp/docker_build_binarydeb"]
+ echo # END SECTION
# END SECTION
+ echo # BEGIN SECTION: Build Dockerfile - binarydeb task
# BEGIN SECTION: Build Dockerfile - binarydeb task
+ cd <http://54.183.26.131:8080/job/Jbin_uT64__calibration_setup_helper__ubuntu_trusty_amd64__binary/ws/docker_generating_docker>
+ python3 -u <http://54.183.26.131:8080/job/Jbin_uT64__calibration_setup_helper__ubuntu_trusty_amd64__binary/ws/ros_buildfarm/scripts/misc/docker_pull_baseimage.py>
Get base image name from Dockerfile 'Dockerfile': ubuntu:trusty
Check docker base image for updates: docker pull ubuntu:trusty
Repository ubuntu already being pulled by another client. Waiting.
Build timed out (after 120 minutes). Marking the build as failed.
[ssh-agent] Stopped.
Build was aborted
[description-setter] Could not determine description.
```

**Comment by tfoote** [comment]
It seems there was an issue last night with the registry. I found this on the master too. Any repeated calls to docker pull ubuntu:trusty would fail as well. 

It seems if you interrupt the pull command it keeps running in the background: https://github.com/docker/docker/issues/3115 And subsequent calls will fail while the pull is still happening. If the pull hangs the only recourse is to restart docker...

["It's no longer possible for a pull to hang in such a way that it would have to be aborted."](https://github.com/docker/docker/issues/3115#issuecomment-48492374) does not seem to hold anymore as we encountered this on several machines last night and I found jobs still running after hours, blocking on the docker pull command. #55 Unfortunately if we add the timeout it appears that without the ability to clear the hung pulls all subsequent pulls will fail as well.

**Comment by tfoote** [comment]
Another machine went bad with this same error. All jobs timing out after 2 hours waiting for the docker pull of ubuntu:trusty

**Comment by tfoote** [comment]
Another instance over the weekend. I'll file a ticket upstream.

**Comment by tfoote** [comment]
There's still some ongoing issues upstream, but the frequency is much lower such that we don't see this often now. Closing

**Comment by dirk-thomas** [comment]
I am pretty sure this is not resolved yet. According to the docker ticket no. 9718 it might be in the upcoming version 1.9.

**Comment by tfoote** [comment]
The upstream ticket is still open, since there appear to be several causes and not all are solved. However I've run ~ 10,000+ jobs in the last weeks and have not run into an instance of this issue. The upgrade to 1.7.1 I believe has fixed our version. If anything it should get better as we move forward and go to the newer versions of docker with more of the upstream fixes. I don't think there's anything we can do about this ticket now except wait for more full fixes upstream.

**Comment by dirk-thomas** [comment]
Which ticket are you referring to? The one I mentioned is closed.

**Comment by tfoote** [comment]
I was referring to 12823 which is the ticket I filed upstream. 9718 is for devicemapper we're back to using aufs

**Comment by dirk-thomas** [comment]
15603 is for AUFS and has been closed recently (as a comment on your ticket states).
