### ISSUE TITLE
trigger-broken-with-non-broken-upstream triggers too many jobs

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/ros_buildfarm#560]
Noticed this recently when triggering `Brel_trigger-broken-with-non-broken-upstream` [also triggered the arm jobs](http://build.ros2.org/job/Brel_trigger-broken-with-non-broken-upstream/25/console) making `Brel_ubv8_trigger-broken-with-non-broken-upstream` [ineffective](http://build.ros2.org/job/Brel_ubv8_trigger-broken-with-non-broken-upstream/24/console).

The issue comes from the fact that we use the [view prefix](https://github.com/ros-infrastructure/ros_buildfarm/blob/31ab207729055747c64f726c9c45b8f28e2f1ad0/scripts/release/generate_release_maintenance_jobs.py#L159) to match the jobs to retrigger.

While the view prefix returns the a specific enough prefix for arm platforms:
```
>>> common.get_release_binary_view_prefix('bouncy', 'ubv8')
'Bbin_ubv8'
```

It returns only a very generic prefix when using the default build file:
```
>>> common.get_release_binary_view_prefix('bouncy', 'default')
'Bbin'
```
A more specific prefix can be used but is specific to a single target of the build file
```
>>> common.get_release_binary_view_name('bouncy', 'default', 'ubuntu', 'bionic', 'amd64')
'Bbin_uB64'
```

We could solve this in several ways, but it depends what is the expected set of job and behaviors we expect (I'll use melodic as an example).

- The `Mrel_trigger-broken-with-non-broken-upstream` is a "catchall" job that triggers all jobs including the ones generated by other build files
  - Change nothing
- The `Mrel_trigger-broken-with-non-broken-upstream` should trigger only the jobs defined in the `default` build file:
  - We need to change the job configuration to take a list of prefixes ([`Mbin_uA64`, `Mbin_uB64`) and modify [_get_trigger_broken_with_non_broken_upstream_job_config](https://github.com/ros-infrastructure/ros_buildfarm/blob/31ab207729055747c64f726c9c45b8f28e2f1ad0/scripts/release/generate_release_maintenance_jobs.py#L152) to return the list of all prefixes generated with the provided build file.
  - Modify the [job template](https://github.com/ros-infrastructure/ros_buildfarm/blob/31ab207729055747c64f726c9c45b8f28e2f1ad0/ros_buildfarm/templates/release/release_trigger-broken-with-non-broken-upstream_job.xml.em#L46-L47) to do the expansion and matching on each of these prefixes.
- (for completeness) Have one of these jobs per target instead of one per build file

**Comment by tfoote** [comment]
Yeah, we've been knowingly living with the catchall behavior. But it would be cleaner to be able to trigger only the default buildfile contents, and not chain to the alternative build targets. But so far we're triggering both simultaneously so it doesn't really make a difference.

One other approach would be to have one job per target, and a meta job per buildfile that will just trigger the target specific jobs.
