### ISSUE TITLE
buildfarm (trusty): python3-catkin-pkg-modules ... has premature member 'control.tar.xz' before 'control.tar.gz'

### ISSUE THREAD

**Issue by mintar** [ros-infrastructure/ros_buildfarm#565]
In the past few days, the Trusty buildfarm started to fail on my packages with messages like these:

```
23:45:32 Unpacking python3-pyparsing (2.0.1+dfsg1-1build1) ...
23:45:32 dpkg-deb: error: archive '/var/cache/apt/archives/python3-catkin-pkg-modules_0.4.7-1_all.deb' has premature member 'control.tar.xz' before 'control.tar.gz', giving up
23:45:32 dpkg: error processing archive /var/cache/apt/archives/python3-catkin-pkg-modules_0.4.7-1_all.deb (--unpack):
23:45:32  subprocess dpkg-deb --control returned error exit status 2
```

Full log: http://build.ros.org/job/Ibin_uT32__mir_msgs__ubuntu_trusty_i386__binary/3/console

I believe this is an instance of this bug: https://github.com/ros-infrastructure/catkin_pkg/issues/227

The **solution** would be to upgrade the `dpkg` package on the Trusty buildfarm to version `1.17.5ubuntu5.8`. Either by updating the base image, or by running this line:

```bash
sudo apt-get install -y dpkg
```

I've had to do the exact same thing for Travis: https://github.com/dfki-ric/mir_robot/commit/0852ab706b974cce9e87e0fd0dd77611e19fe620

**Comment by gavanderhoorn** [comment]
I believe #564 took care of this, but it may not have been deployed everywhere yet.

**Comment by mintar** [comment]
For people who don't see your edit in the email notifications: that only deals with the `.travis` config.

**Comment by mintar** [comment]
I believe @dirk-thomas is the one who should look at this?

**Comment by dirk-thomas** [comment]
Please try #566 and comment if that patch address the problem for you.

**Comment by dirk-thomas** [comment]
~~Please try #566 and comment if that patch address the problem for you.~~ I modified the referenced job to use the branch of #566.

**Comment by mintar** [comment]
Yup, that worked. The referenced job just passed.

**Comment by dirk-thomas** [comment]
The latest build of the referenced job has passed using changes from the PR: http://build.ros.org/job/Ibin_uT32__mir_msgs__ubuntu_trusty_i386__binary/4/
