### ISSUE TITLE
doc job failing for interfaces relying on messages in non standard location?

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/ros_buildfarm#572]
The doc job documentation currently lists known limitations one of witch being:
`Message files in non-standard locations will not be recognised and therefore no code will be generated for them`

We faced a corner case of this where services in standard location depend on messages in non-standard location resulting in the doc job to fail ([doc job](http://build.ros.org/view/Idoc/job/Idoc__cartographer_ros__ubuntu_trusty_amd64/151)).

Is it the expected behavior? or should these messages/services be ignored and the other ones built and the job passing?

**Comment by dirk-thomas** [comment]
This sounds like a duplicate of #292.

**Comment by mikaelarguedas** [comment]
I did see #292  but figured it may deserve a separate issue as in this case there is no "custom CMake logic" just regular calls to `add_messages_files` and `generate_messages` and it seemed that it was in the scope of what the [doc jobs want to accomplish](https://github.com/ros-infrastructure/ros_buildfarm/issues/292#issuecomment-217942416):
```
Doc jobs don't perform real builds but replace the package CMake file with a simplified template which only tries to generate messages. So all your custom CMake logic is not being used.
```
The goal of this issue is just to know "what would be a better behavior?" to have hints of what improvement could be PR'd.
Would we prefer having a way to build all interface files regardless of their location as specified in the original CMakeLists?
Or to just ignore the ones we know cannot be satisfied and try to build the rest ?

**Comment by dirk-thomas** [comment]
> in this case there is no "custom CMake logic" just regular calls to `add_messages_files` and `generate_messages`

Yes, there is. The custom logic is coming from the buildfarm itself. Instead of using the package provided CMake logic to build the package (which knows best which msg/srv files to process and which not to) the doc jobs replace the CMake code with a [generic CMake snippet](https://github.com/ros-infrastructure/ros_buildfarm/blob/a9f0554840dda39272d76ff19f67c1675d77f8d6/ros_buildfarm/templates/doc/CMakeLists.txt.em) which just checks the standard locations and processes the found msg/srv files.

The problematic package used `.msg` files in a non-standard location which the "generic CMake snippet" doesn't know about and there doesn't consider.

> The goal of this issue is just to know "what would be a better behavior?" to have hints of what improvement could be PR'd.
> Would we prefer having a way to build all interface files regardless of their location as specified in the original CMakeLists?
> Or to just ignore the ones we know cannot be satisfied and try to build the rest ?

The doc job should build exactly the same msgs/srvs as the CMake code contained in the package - however that is achieved. Just performing a regular build (without modifying the CMake code is likely the only reasonable way to do so).

In this case it would also be feasible to just update the package to place all msg files in the standard location and the problem would go away.

**Comment by mikaelarguedas** [comment]
> The custom logic is coming from the buildfarm itself. Instead of using the package provided CMake logic to build the package (which knows best which msg/srv files to process and which not to) the doc jobs replace the CMake code with a generic CMake snippet which just checks the standard locations and processes the found msg/srv files.
> In this case it would also be feasible to just update the package to place all msg files in the standard location and the problem would go away.

Agreed on both of these :+1:  that is the suggestion offered upstream: https://github.com/googlecartographer/cartographer_ros/issues/1016#issuecomment-421367510

> The doc job should build exactly the same msgs/srvs as the CMake code contained in the package - however that is achieved. Just performing a regular build (without modifying the CMake code is likely the only reasonable way to do so).

Fair enough I was thinking of something like just keeping the calls to `add_messages_files` (service and actions) and `generate_messages` from upstream but not execute the rest of the CMake code. But if we're fine just performing a regular build that is good too.

Closing as duplicate then as performing a regular build is the suggestion in https://github.com/ros-infrastructure/ros_buildfarm/issues/292

**Comment by dirk-thomas** [comment]
> I was thinking of something like just keeping the calls to `add_messages_files` (service and actions) and `generate_messages` from upstream but not execute the rest of the CMake code.

How would you want to do this? The part which triggers the message generation might contain arbitrary CMake logic. I don't see how you could "extract" / "isolate" that in an automatic way.

> But if we're fine just performing a regular build that is good too.

The corresponding ticket has been open for 2+ years so I don't expect this to change.

**Comment by mikaelarguedas** [comment]
> How would you want to do this? The part which triggers the message generation might contain arbitrary CMake logic. I don't see how you could "extract" / "isolate" that in an automatic way.

That is a good point, I assumed they would not be in custom cmake blocks but just because no packages that I've seen so far doesn't mean that it can't happen.
