### ISSUE TITLE
Saucy was just pulled from archive.ubuntu.com

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#58]
We need to either switch to http://old-releases.ubuntu.com/releases/ or turn them off.

@dirk-thomas @wjwwood FYI

**Comment by tfoote** [comment]
The saucy tag is not on the supported list any more: https://registry.hub.docker.com/_/ubuntu/

We may need to roll our own now. Otherwise there's only a few places we will need to update from a quick search: https://github.com/ros-infrastructure/ros_buildfarm/search?utf8=%E2%9C%93&q=archive&type=Code

**Comment by dirk-thomas** [comment]
Since we have not communicated this topic with the community we have to continue building Saucy packages for now. Please go ahead and make a PR for this. I have already patched the old farm last night: https://github.com/ros-infrastructure/buildfarm/commit/1c88f7640eba35675e2fa2011f51a0c61fb6008a

**Comment by tfoote** [comment]
I've tested this sed script on a local docker container and it gets apt running
`find /etc/apt/ -name *.list -exec sed -i -e 's/archive.ubuntu.com\|security.ubuntu.com/old-releases.ubuntu.com/g'  {} \;`

Modified [from here](http://unix.stackexchange.com/questions/146551/apt-get-cant-find-the-package-on-a-old-version-of-my-distro)

We will just need to embed that into the Dockerfiles for old-releases.
