### ISSUE TITLE
build-and-test stage uses install space from build-and-install stage

### ISSUE THREAD

**Issue by rhaschke** [ros-infrastructure/ros_buildfarm#581]
In https://github.com/ros-planning/moveit/issues/1106 we observed a strange failure of the pre-release test.
The problem was on the one hand induced [by circular package dependencies](https://github.com/ros-planning/moveit/issues/1106#issuecomment-431831861).
However, there is another problem, which I first thought is [related to catkin's](https://github.com/ros-planning/moveit/issues/1106#issuecomment-432017181) function `list_insert_in_workspace_order()`.

However, digging deeper I found that the issue is actually related to the build farm. This also explains that I only observed the issue when building a full pre-release test, but not when building only the build-and-test stage.

Running **`build-and-install`**, catkin uses these variables:
```
CATKIN_DEVEL_PREFIX=/tmp/catkin_workspace/devel_isolated/moveit_moveit_ros_move_group
CATKIN_WORKSPACES=/tmp/catkin_workspace/install_isolated;/opt/ros/indigo
```
and finds libraries (and includes) at the correct location: 
* raw libs: `/tmp/catkin_workspace/install_isolated/lib;/opt/ros/indigo/lib`
* ordered libs: `/tmp/catkin_workspace/install_isolated/lib;/opt/ros/indigo/lib`

Subsequently running **`build-and-test`** yields:
```
CATKIN_DEVEL_PREFIX=/tmp/catkin_workspace/devel_isolated/moveit_moveit_ros_move_group
CATKIN_WORKSPACES=/tmp/catkin_workspace/devel_isolated/moveit_*;/opt/ros/indigo
```
However, includes and libs are still found in `install_isolated`, which shouldn't happen I think, and yields the wrong order of directories (because install_isolated is handled as "non-catkin" by `list_insert_in_workspace_order()`:
* raw libs: `/tmp/catkin_workspace/install_isolated/lib;/opt/ros/indigo/lib`
* ordered libs: `/opt/ros/indigo/lib;/tmp/catkin_workspace/install_isolated/lib`

Finally, running **`build-and-test` _alone_** yields the correct paths:
* raw libs: `/tmp/catkin_workspace/devel_isolated/*/lib;/opt/ros/indigo/lib;/tmp/catkin_workspace/devel_isolated/*/lib`
* ordered libs: `/tmp/catkin_workspace/devel_isolated/*/lib;/opt/ros/indigo/lib`

I think the reason for this wrong behaviour is that cmake caches its results and doesn't attempt to find_package them again during `build-and-test` stage, although the environment has changed.

Full logs are available here:
https://gist.github.com/rhaschke/aade4ac7286207cedd18c602ef128755#file-build-install-test-log
https://gist.github.com/rhaschke/aade4ac7286207cedd18c602ef128755#file-build-test-log

**Comment by dirk-thomas** [comment]
Please share the steps to reproduce the problem.

> I think the reason for this wrong behaviour is that cmake caches its results and doesn't attempt to find_package them again during `build-and-test` stage, although the environment has changed.

`colcon` offers the option `--cmake-clean-cache` for that case. Maybe something similar is needed here for `catkin_make_isolated`.

**Comment by rhaschke** [comment]
> Please share the steps to reproduce the problem.

All details were given as links, e.g. prerelease commands [here](https://github.com/ros-planning/moveit/issues/1106).

> colcon offers the option --cmake-clean-cache for that case. Maybe something similar is needed here for catkin_make_isolated.

I think this is the correct conclusion. When running the install phase - due to the not cleaned cache - cmake finds libraries in `catkin_workspace/install_isolated`, which is simply wrong.

**Comment by rhaschke** [comment]
It wasn't the `generator` script that failed, but the `prerelease` one. Also, the bug found in https://github.com/ros-planning/moveit/issues/1106 required to ingredients:
1. A circular package dependency (which is meanwhile fixed)
2. The prerelease test re-using cmake caches from build-and-install to build-and-test phase.

As the first issue is fixed, you cannot easily reproduce the 2nd issue anymore.
By the way, an alternative to providing a  `--cmake-clean-cache` option to catkin, is to simply ensure that different build spaces are used for both phases.

**Comment by dirk-thomas** [comment]
> simply ensure that different build spaces are used for both phases.

The downside of that approach is that it prevents reusing any of the already create artifacts.

#591 might address the case described in this issue. I just can't say for certain without a reproducible example.
