### ISSUE TITLE
[pre-release test] Detect non-released package 

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/ros_buildfarm#584]
Although I'm not sure if pre-release test is the right place to do this.

During `bloom`, I found one of the package that is depended in a package bloom tries to release is not yet released (detail https://github.com/ros-planning/moveit/issues/1083#issuecomment-432622738).

IMO pre-release test is a good place to capture this.
It was not captured the pre-release test (below is the commands used to run).

```
$ _DIR_PRLTEST=/tmp/prerelease_job_xen-kin; mkdir -p $_DIR_PRLTEST && cd $_DIR_PRLTEST
$ generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml kinetic default ubuntu xenial amd64  moveit   --level 0  --output-dir ./
$ ./prerelease.sh 
```

**Comment by dirk-thomas** [comment]
A prerelease runs *before* the release / `bloom`. Therefore I doesn't have any knowledge about what package might be excluded during a later release. It uses the source repository - not the release repository where the information about ignoring packages is stored / defined.
