### ISSUE TITLE
Broken package pyside2 on ros melodic 

### ISSUE THREAD

**Issue by mcsheehan** [ros-infrastructure/ros_buildfarm#603]
The pyside2 package on melodic is broken. Steps to reproduce.
Spin up a docker container using ubuntu 18:04
Add ros repositories.
Try to install pyside2 from ros repositories -> Fail.
This means that at present on melodic no-one can make guis without paying for a  pyqt license or being GPL licensed.

Here's a copy paste of bash commands to reproduce it for ease of confirmation:
docker run -it --entrypoint bash ubuntu:18.04
apt-get update 
apt-get install --yes gnupg2 software-properties-common
echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
apt-get update
apt-get install python-pyside2

Fail:

The following packages have unmet dependencies:
 python-pyside2 : Depends: python-pyside2.qtconcurrent (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtcore (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtgui (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qthelp (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtmultimedia (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtnetwork (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtopengl (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtprintsupport (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtqml (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtquick (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtquickwidgets (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtscript (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtsql (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtsvg (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qttest (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtuitools (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtwebchannel (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtwebkit (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtwebkitwidgets (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtwebsockets (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtwidgets (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtx11extras (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed
                  Depends: python-pyside2.qtxml (>= 2.0.0+dev-0~201712291010~rev1791~pkg76~ubuntu18.04.1) but it is not going to be installed

**Comment by dirk-thomas** [comment]
The version of PySide2 available on Bionic is only a pre-release which unfortunately doesn't work well. In the mean time PySide2 had changed to only support Python 3. So until ROS Noetic in May 2020 this is not going to be fixed.

**Comment by mcsheehan** [comment]
Then maybe you should consider removing the load of pyside2 broken packages from your provided packages if it they don't work? It was a time sink discovering this and I can't imagine you want ros becoming a minefield of won't fix broken packages.
