### ISSUE TITLE
Unpin sphinx version

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#616]
We have pinned the version of sphinx in #615 to resolve the failing builds in #614 

We will want to unpin the version in the future to avoid falling behind. It may be that there's an upstream patch release that resolves the issue or that we need to change our approach. But this ticket is here to make sure we won't forget.

Note that the 2.0.1 patch release that came out a few hours ago didn't resolve it. http://build.ros.org/job/doc_independent-packages/1205/console

**Comment by dirk-thomas** [comment]
@tfoote Please try again with the latest release to check if we can revert the pinning.

**Comment by dirk-thomas** [comment]
@tfoote Friendly ping.

**Comment by dirk-thomas** [comment]
@tfoote Another friendly ping.

**Comment by tfoote** [comment]
It's still failing. http://build.ros.org/job/doc_independent-packages/195/console

It looks like we need a higher version of python available for the latest version of sphinx.

```
01:32:44 Collecting catkin-sphinx
01:32:44   Downloading https://files.pythonhosted.org/packages/59/80/f3166bf20d20a9cb1c8ee1b5c09e5050241ee58ba717b454b5de23204f2f/catkin-sphinx-0.2.2.tar.gz
01:32:44 Collecting sphinx
01:32:44   Downloading https://files.pythonhosted.org/packages/60/e8/dae78b653ef073b2a84755f755c51d39290f2f95c671671495cd2b9a4849/Sphinx-2.2.2.tar.gz (5.8MB)
01:32:45     Complete output from command python setup.py egg_info:
01:32:45     ERROR: Sphinx requires at least Python 3.5 to run.
01:32:45     
01:32:45     ----------------------------------------
01:32:45 [91mCommand "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fvulKN/sphinx/
```

**Comment by dirk-thomas** [comment]
The dependency has been moved into the config file since then. ros-infrastructure/ros_buildfarm_config#164 unpins it.
