### ISSUE TITLE
ROS1/ROS2 Hybrid Packages Fail to Build

### ISSUE THREAD

**Issue by JWhitleyAStuff** [ros-infrastructure/ros_buildfarm#620]
Packages using the `condition=` attribute in `package.xml` files conforming to the Format 3 specification (defined in [REP-149](http://www.ros.org/reps/rep-0149.html#id8)) fail to pass `dev` and `bin` builds on the Crystal build farm. Example:

http://build.ros2.org/job/Cdev__ml_classifiers__ubuntu_bionic_amd64/lastBuild/console
http://build.ros2.org/job/Cbin_uB64__ml_classifiers__ubuntu_bionic_amd64__binary/1/console

The log in the `dev` job seems to indicate a failure in package resolution in `rosdep2`. The same failure is causing the `dev` jobs for Kinetic, Lunar, and Melodic to fail as well on the same package:

http://build.ros.org/job/Kdev__ml_classifiers__ubuntu_xenial_amd64/4/console
http://build.ros.org/job/Ldev__ml_classifiers__ubuntu_xenial_amd64/4/console
http://build.ros.org/job/Mdev__ml_classifiers__ubuntu_xenial_amd64/4/console

Locally, I used `rosdep` to check dependencies and it worked correctly. Testing locally with `rosdep2` reveals the same issue. I've logged an issue for it over at ros-infrastructure/rosdep#676 to handle this one.

As for the CMake error on the `bin` build on Crystal, I'm not really sure where to start debugging. Is there a set of steps I can run locally to re-create the environment and look at some logs? Any help would be appreciated.

**Comment by dirk-thomas** [comment]
Your package is the first one being processed on the buildfarm which uses the condition attributes to select between ROS 1 and ROS 2. Somewhere in the pipeline there is a problem since nobody has ever tried that.

> Is there a set of steps I can run locally to re-create the environment and look at some logs?

https://github.com/ros-infrastructure/ros_buildfarm/blob/b53e237e46f2455b85a674e1a9edb0f67f6e2a2b/doc/jobs/devel_jobs.rst#run-the-devel-job-locally

**Comment by tfoote** [comment]
@JWhitleyAStuff  I think that the conditional logic needs to be added to these two functions: 

https://github.com/ros-infrastructure/ros_buildfarm/blob/70ed97bf71302356e99dbc6d1e3a4e24a4eb7f62/scripts/devel/create_devel_task_generator.py#L193

and 
https://github.com/ros-infrastructure/ros_buildfarm/blob/70ed97bf71302356e99dbc6d1e3a4e24a4eb7f62/scripts/devel/create_devel_task_generator.py#L222

Which are passed into https://github.com/ros-infrastructure/ros_buildfarm/blob/70ed97bf71302356e99dbc6d1e3a4e24a4eb7f62/scripts/devel/create_devel_task_generator.py#L179

Which is called at:
https://github.com/ros-infrastructure/ros_buildfarm/blob/70ed97bf71302356e99dbc6d1e3a4e24a4eb7f62/scripts/devel/create_devel_task_generator.py#L119
and
https://github.com/ros-infrastructure/ros_buildfarm/blob/70ed97bf71302356e99dbc6d1e3a4e24a4eb7f62/scripts/devel/create_devel_task_generator.py#L128

**Comment by JWhitleyAStuff** [comment]
@tfoote - Thanks for the hints. I'm working on a PR now.

@dirk-thomas - In order to add the same conditional logic that is included in Bloom (querying the index to get the `rosdistro` version), a lot of bloom common code - nearly all of [`rosdistro_api.py`](https://github.com/ros-infrastructure/bloom/blob/master/bloom/rosdistro_api.py) and some of [`github.py`](https://github.com/ros-infrastructure/bloom/blob/master/bloom/github.py) - would need to be ported. If there is an easier way to get the ROS_VERSION than querying the index and you're happy using it, then that's OK with me. Otherwise, I either need to:

1. Port the above-mentioned files from Bloom to get the same functionality or;
2. Make the build scripts depend on Bloom.

Either way, we will create a dependency on `rosdistro` in order to get the info. Please let me know your preferred method.

**Comment by dirk-thomas** [comment]
> I either need to:
> * Port the above-mentioned files from Bloom to get the same functionality or;
> * Make the build scripts depend on Bloom.

Neither of this is necessary / desired.

> we will create a dependency on rosdistro in order to get the info.

`ros_buildfarm` already depends on `rosdistro`: https://github.com/ros-infrastructure/ros_buildfarm/blob/b53e237e46f2455b85a674e1a9edb0f67f6e2a2b/setup.py#L64

The `rosdistro` API is sufficient to query all the information available from the `ros/rosdistro` repository. No need to pull in any code from `bloom` for that.

**Comment by dirk-thomas** [comment]
`devel` jobs should be fixed by #621.

The `release` job should be fixed by ros-infrastructure/bloom#519. Can you try to re-release with at least `bloom` 0.8.0?

**Comment by JWhitleyAStuff** [comment]
Thanks for working on this, @dirk-thomas. I hadn't gotten back around to it yet. I've merged your PR to `ml_classifiers` and I'll release again once #621 has been merged.

**Comment by dirk-thomas** [comment]
> I'll release again once #621 has been merged.

The release is independent of the changes to the devel job (anyway it has been merged). You just need a current version of `bloom`.

**Comment by dirk-thomas** [comment]
@JWhitleyAStuff The latest `bloom` release only created a Debian increment of the previous upstream release. You do need to make a new upstream patch release though to include the recently merged fix from astuff/ml_classifiers#3 and then call `bloom` again.

**Comment by JWhitleyAStuff** [comment]
I've re-released with 0.8.0. I'll try to work on the CMake failure. Thanks to both of you for your help.

**Comment by JWhitleyAStuff** [comment]
Sorry. Derp. Releasing as 1.0.1.

**Comment by JWhitleyAStuff** [comment]
Looks like everything on the farm is happy. Thanks!

**Comment by dirk-thomas** [comment]
:tada:

* http://build.ros2.org/job/Cdev__ml_classifiers__ubuntu_bionic_amd64/6/
* http://build.ros2.org/job/Cbin_uB64__ml_classifiers__ubuntu_bionic_amd64__binary/8/
* http://build.ros.org/job/Kdev__ml_classifiers__ubuntu_xenial_amd64/5/
* http://build.ros.org/job/Ldev__ml_classifiers__ubuntu_xenial_amd64/6/
* http://build.ros.org/job/Mdev__ml_classifiers__ubuntu_bionic_amd64/6/

Thanks for iterating on this quickly.
