### ISSUE TITLE
are pip dependencies from rosdep handled correctly?

### ISSUE THREAD

**Issue by moriarty** [ros-infrastructure/ros_buildfarm#643]
We've recently https://github.com/fetchrobotics/fetch_robots/pull/45 added a dependency to `ds4drv-pip` and now our PR jobs are failing.

when I run: `rosdep resolve ds4drv-pip` it returns
```
#pip
ds4drv
```

However it seems that the buildfarm is treating it as an apt dependency.

Is it the case that pip dependencies are not handled?

**Comment by moriarty** [comment]
FYI @tfoote, @dirk-thomas and @clalancette there is now a GitHub feature to automatically assign and label issues with some github templates similar to the way the `CODEOWNERS` file can automatically assign reviewers.

Here is a simple example:
https://github.com/fetchrobotics/fetch_ros/commit/880926209e91da7286b075fcd7c0ee665fa54243

**Comment by moriarty** [comment]
It looks like the `doc` jobs are also not handling `pip` dependencies, but at least they are just causing warnings and not failures.
https://github.com/ros-infrastructure/ros_buildfarm/blob/70ed97bf71302356e99dbc6d1e3a4e24a4eb7f62/scripts/doc/create_doc_task_generator.py#L544-L554

A quick fix might be to assume a `KeyError` should try to be installed using pip.

**Comment by paulbovbel** [comment]
@moriarty, you'll find that the buildfarm does not support pip packages https://answers.ros.org/question/313811/bloom-generate-debian-package-with-pip-only-dependency/

Shameless plug, try out https://github.com/locusrobotics/catkin_virtualenv to get around that kind of thing. Your other approaches are to either vendor the library, or work with the author on getting it into debian.

**Comment by moriarty** [comment]
Thanks

**Comment by moriarty** [comment]
I looked into adding this here, but it's a lot more effort than I expected.

@erelson has made a proposal to ensure we've got `ds4drv` installed on our robots for now and we'll try to come up with a more elegant solution in the future.
