### ISSUE TITLE
Issue compiling against Boost 1.69+

### ISSUE THREAD

**Issue by exoticDFT** [ros-infrastructure/ros_buildfarm#651]
There seems to be a few issues with installing ROS from source on Fedora 30. Although one issue has been somewhat addressed with the `rosdep` parts of the installation process, there is an issue with compiling any package that uses (or at least cmake checks for) Boost's `signals` library.

The issue here seems to be due to the fact that Fedora 30 comes with [boost 1.69, which completely removed the deprecated `signals` library](https://www.boost.org/users/history/version_1_69_0.html). I found this [repo](https://github.com/kwrazi/archlinux-ros-melodic) of tools for installing ROS on Arch, which includes a script for fixing a single CMakeLists.txt that searches for Boost `signals`. However, this script is specific to Arch installation and won't work without modification. I manually removed `signals` from the `tf2` package and was able to compile this package correctly. I have not attempted all other packages that require `signals` yet.

Since it seems that `signals` has been deprecated for a long time and the replacement, `signals2`, is a header only library, it should be possible to drop `signals` from `find_package(Boost REQUIRED COMPONENTS signals ...)` within the CMakeLIsts.txt files throughout ROS.

**Comment by dirk-thomas** [comment]
This repository only contains the code running the buildfarm logic therefore the issue isn't related to this repo. Hence I will close the ticket.

Please create issues (or even better pull requests) in the repositories which actually do contain code which uses Boost  `signals`>
