### ISSUE TITLE
Excessive CPU usage when building Dockerfiles

### ISSUE THREAD

**Issue by mm318** [ros-infrastructure/ros_buildfarm#654]
When building some Dockerfiles as part of the prerelease flow, we are getting stuck at the step:
```
Step 9/25 : RUN useradd -u 629291812 -m buildfarm
```
with excessively high CPU usage. This is apparently an issue with Docker (https://forums.docker.com/t/run-adduser-seems-to-hang-with-large-uid/27371/2)

As a workaround can you please modify your Dockerfile to do something like
```
useradd -u @uid -l -m buildfarm
```
instead?

**Comment by dirk-thomas** [comment]
The Dockerfiles generated by this package don't use a hard coded `uid`. Instead they use the `uid` of the current user outside of Docker in order to ensure that the generated files in mounted directories can be read / written by the calling user.

You might want to double check the user id you are invoking the script with: `echo $UID`.

**Comment by mm318** [comment]
I'm not asking for the Dockerfiles generated by this package to use a different UID.

I'm asking for the Dockerfiles generated by this package to use an additional `-l` or `–no-log-init` option for the `useradd` command, as suggested in https://forums.docker.com/t/run-adduser-seems-to-hang-with-large-uid/27371.

**Comment by dirk-thomas** [comment]
Thanks for clarifying. So your local UID is that high and you would like to use `-l` / `--no-log-init` with `useradd`.

Please consider to create a pull request for this change in all locations where `useradd` is being invoked.

**Comment by mm318** [comment]
Right, our local UID is that high probably because we are on corporate machines. I will make the pull request. Thanks!
