### ISSUE TITLE
scripts get installed into the wrong locations when using pip

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#66]
I had to add symlinks to get an installation via pip to work.  below is 4 examples I fixed. There are close to a dozen which need links.

```
$ ls -l misc/ status/ doc
doc:
total 0
lrwxrwxrwx 1 tfoote tfoote 34 Apr 29 13:44 generate_doc_independent_job.py -> ../generate_doc_independent_job.py

misc/:
total 4
lrwxrwxrwx 1 tfoote tfoote 74 Apr 29 13:35 generate_dashboard_job.py -> /home/tfoote/work/dbf/ros_buildfarm/scripts/misc/generate_dashboard_job.py
lrwxrwxrwx 1 tfoote tfoote 34 Apr 29 13:57 generate_rosdistro_cache_job.py -> ../generate_rosdistro_cache_job.py

status/:
total 0
lrwxrwxrwx 1 tfoote tfoote 38 Apr 29 14:05 generate_release_status_page_job.py -> ../generate_release_status_page_job.py
```

**Comment by dirk-thomas** [comment]
I can install the package via pip3 install fine and find all scripts in the bin folder. Can you please post exact steps of what you did and what was not working then?

**Comment by tfoote** [comment]
I lost the console output from this invocation in a hard freeze of my computer. 

I ran the instructions from: https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/environment.rst  (modified to checkout jenkinsapi=0.2.26 ) The execute `generate_all_jobs.py` with the rosdistro. 

The scripts in the bin folder are the problem. It's looking for them in subdirectories like they are in the scripts directory. It's trying to invoke the scripts with the subdirectory such as 'misc/generate_dashboard_job.py` and is failing to find that in the installation.

**Comment by dirk-thomas** [comment]
Bu the scripts like `generate_dashboard_job.py` are in the `bin` folder and you can invoke them because they are on the path in the virtualenv?

**Comment by dirk-thomas** [comment]
I think the problem is that the `generate_all_jobs` uses relative path to the other scripts which are wrong after installation since all scripts are siblings at that point.
