### ISSUE TITLE
Implementation of abichecker for ROS2

### ISSUE THREAD

**Issue by j-rivero** [ros-infrastructure/ros_buildfarm#678]
To implement the ABI checking of ROS2 package I have some doubts that would like to resolve before starting the works:

* Which scenarios should be covered by the ABI checking? I'm pretty sure that we probably want it for PR testing to check changes against current stable version. Any other context (check testing against stable, ...)?

* How are we going to identify which packages needs ABI checking? Adding an option in build/release files is the first thing that comes to my mind, not sure if we have a better idea.

* Do we need to create new jobs for ABI checking or should we try to reuse the existing ones? In the case of PR testing, the abi-checking can be added to existing `[A-Z]pr__` jobs. Please note that ABI checking requires the use of `-g -Og` flags during compilation so we can not reuse the current pr__ build.

**Comment by j-rivero** [comment]
After speaking with @chapulina and start working on the project, I've some updates for some of my questions:

>     * Which scenarios should be covered by the ABI checking? I'm pretty sure that we probably want it for PR testing to check changes against current stable version. Any other context (check testing against stable, ...)?

The PR testing jobs are main and natural scope for running the ABI checking. The best option is to test ABI against the stable .deb packages.

>     * How are we going to identify which packages needs ABI checking? Adding an option in build/release files is the first thing that comes to my mind, not sure if we have a better idea.

Still an open question.

>     * Do we need to create new jobs for ABI checking or should we try to reuse the existing ones? In the case of PR testing, the abi-checking can be added to existing `[A-Z]pr__` jobs. Please note that ABI checking requires the use of `-g -Og` flags during compilation so we can not reuse the current pr__ build.

I've checked that the tool can perfectly run on code compiling without special debug flags so the fastest and easiest way would be to use the compiled code in the existing PRs.

**Comment by dirk-thomas** [comment]
> How are we going to identify which packages needs ABI checking?

It probable depends on how much overhead this check adds to a job. If it is fairly minor I don't see a reason why not to do it for every package / repo.

> the abi-checking can be added to existing `[A-Z]pr__` jobs

It might be good to not only run the check in PR jobs but also in devel jobs to keep seeing the notice / warning more than once. Otherwise after merging a PR there will be no further notifications.

**Comment by j-rivero** [comment]
Summarizing: 

* Existing PR jobs (named `[a-Z]pr__`) and devel jobs (named `[a-Z]dev__`) are under the scope of this work and should run the abichecker. The abichecker is going to be part of the existing jobs and reacting to the commits and changed that are in the current working pipeline. 
* The initial proposal will cover the use of the checker for all the jobs, measuring the execution time of each one and not failing in those that don't provide any header or library file.

**Comment by j-rivero** [comment]
All the initial support has been merged. Thanks everyone involved. Closing .
