### ISSUE TITLE
CMAKE_INSTALL_PREFIX passed twice in dh_auto_configure

### ISSUE THREAD

**Issue by wxmerkt** [ros-infrastructure/ros_buildfarm#686]
I am debugging an issue where a third-party package using `GNUInstallDirs` installs into the wrong directory using the variable `CMAKE_INSTALL_FULL_LIBDIR` (using the system architecture prefix). This variable is set using a special case in `GNUInstallDirs` if `CMAKE_INSTALL_PREFIX=/usr` and there is an architecture set.

Digging deeper into this I realised that the `dh_auto_configure` command passes `-DCMAKE_INSTALL_PREFIX` **twice**. Is this desired?

```
dh_auto_configure -- -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic"
	install -d obj-x86_64-linux-gnu
	cd obj-x86_64-linux-gnu && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_PREFIX=/opt/ros/kinetic
```

**Comment by wxmerkt** [comment]
I think this was a red herring. The real issue I was looking at was described in https://github.com/ros-infrastructure/ros_buildfarm/issues/543#issuecomment-395249636. However I am unclear of whether I should manually change the `rules` in the release or whether there is an easier fix.

**Comment by wxmerkt** [comment]
Is there a reason for passing `CMAKE_INSTALL_PREFIX` twice or could the first `CMAKE_INSTALL_PREFIX=/usr` be removed?

**Comment by dirk-thomas** [comment]
I would guess the first one (`/usr`) is added by the general toolchain and only the second one (`/opt/ros/<distro>`) is set by our tools.
