### ISSUE TITLE
pip dependencies

### ISSUE THREAD

**Issue by mistoll** [ros-infrastructure/ros_buildfarm#764]
AFAIK dependencies which are resolved to pip packages by rosdep aren't supported by ros_buildfarm. That's fine for the release jobs, because they are building debian packages.
For devel jobs support for devel jobs would be nice for running tests.

However, what's interfering me is the fact, that if a repository has two packages, one with pure deb dependencies and one with a pip dependency, the devel job fails without running any tests. ("The cache has no package named ...")

Any thoughts on this issue?
Could we just skip the pip dependencies? Or skip any package with non debian dependencies?
How hard would it be to add pip support to the devel tasks?

**Comment by dirk-thomas** [comment]
> However, what's interfering me is the fact, that if a repository has two packages, one with pure deb dependencies and one with a pip dependency, the devel job fails without running any tests. ("The cache has no package named ...")

Can you please reference a specific build for context.

> Could we just skip the pip dependencies?

That option will likely result in failed builds since the declared dependencies are likely required by the package - otherwise it wouldn't declare them.

> Or skip any package with non debian dependencies?

That doesn't sounds viable either. There might be plain packages with no dependencies which would be skipped with this.

> How hard would it be to add pip support to the devel tasks?

Hard to tell without doing the actual work. If you are interested in this feature I would suggest you try adding this locally to see how many places need to be updated.

**Comment by mistoll** [comment]
> Can you please reference a specific build for context.
This is running on our private buildfarm. Here's the relevant part of the build log:
```
12:34:10 # BEGIN SECTION: Run Dockerfile - generating devel tasks
...
12:35:00 Resolved the dependencies to the following binary packages:
12:35:00   - ros-melodic-catkin
12:35:00 Always install the following generic dependencies:
12:35:00   - build-essential
12:35:00   - python3
12:35:00   - ros-melodic-catkin
12:35:00 Identified the following build dependencies (ignoring packages available from source):
12:35:00   - catkin
12:35:00   - roslint
12:35:00 Resolved the dependencies to the following binary packages:
12:35:00   - ros-melodic-catkin
12:35:00   - ros-melodic-roslint
12:35:00 Identified the following run and test dependencies (ignoring packages available from source):
12:35:00   - python-flask
12:35:00   - **python-flask-cors-pip**
12:35:00   - python-flask-testing
12:35:00   - python-jwt
12:35:00   - python-sqlalchemy
12:35:00   - python-websocket
12:35:00   - roslint
12:35:00 Resolved the dependencies to the following binary packages:
12:35:00   - **flask-cors**
12:35:00   - python-flask
12:35:00   - python-flask-testing
12:35:00   - python-jwt
12:35:00   - python-sqlalchemy
12:35:00   - python-websocket
12:35:00   - ros-melodic-roslint
12:35:00 Traceback (most recent call last):
12:35:00   File "/usr/lib/python3/dist-packages/apt/cache.py", line 289, in __getitem__
12:35:00     return self._weakref[key]
12:35:00   File "/usr/lib/python3.6/weakref.py", line 137, in __getitem__
12:35:00     o = self.data[key]()
12:35:00 KeyError: 'flask-cors'
12:35:00 
12:35:00 During handling of the above exception, another exception occurred:
12:35:00 
12:35:00 Traceback (most recent call last):
12:35:00   File "/usr/lib/python3/dist-packages/apt/cache.py", line 292, in __getitem__
12:35:00     rawpkg = self._cache[key]
12:35:00 KeyError: 'flask-cors'
12:35:00 
12:35:00 During handling of the above exception, another exception occurred:
12:35:00 
12:35:00 Traceback (most recent call last):
12:35:00   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 297, in <module>
12:35:00     main()
12:35:00   File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 147, in main
12:35:00     get_binary_package_versions(apt_cache, debian_pkg_names_testing))
12:35:00   File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 155, in get_binary_package_versions
12:35:00     pkg = apt_cache[debian_pkg_name]
12:35:00   File "/usr/lib/python3/dist-packages/apt/cache.py", line 294, in __getitem__
12:35:00     raise KeyError('The cache has no package named %r' % key)
12:35:00 KeyError: "The cache has no package named 'flask-cors'"
12:35:01 Build step 'Execute shell' marked build as failure
```

> That doesn't sounds viable either. There might be plain packages with no dependencies which would be skipped with this.

IMO it should be possible to come up with some fesible condition for skipping packages. However I dont't think it a good idea. There should be some error - or at least a warning - at the end, because the maintainer must know, that the buildfarm won't run binary tasks for that package. Also IMO boom would have to be updated to reflect those changes.

That beeing said, IMO the effort is not worth the benefits. Nether for skipping nor for installing the dependencies.

For anyone trying to build packages with pip dependencies
WORKAROUND: create debian packages for each pip packages you depend on and depend on the debian packages

**Comment by dirk-thomas** [comment]
> `KeyError: 'flask-cors'`

The error message you are seeing is due to the fact that `flask-cors` is not a valid `rosdep` key. You can't just use a `pip` package name as a dependency. The correct key to use would be `python-flask-cors-pip` as defined here: https://github.com/ros/rosdistro/blob/e3e74b52e6d5518ad502dabfea3815a7277012f4/rosdep/python.yaml#L1524

**Comment by mistoll** [comment]
> 12:35:00   - python-flask-cors-pip
The dependency name is "python-flask-cors-pip".
