### ISSUE TITLE
test results missing

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#77]
geometry_experimental runs many tests. However the reports are only showing 2 tests run. 

Console output of latest build showing all the tests run. 
http://54.183.26.131:8080/view/Idev/job/Idev__geometry_experimental__ubuntu_trusty_amd64/25/consoleFull

The relevant section at the bottom is that xunit is only finding one xml file:
```
00:11:41.402 [xUnit] [INFO] - Starting to record.
00:11:41.402 [xUnit] [INFO] - Processing GoogleTest-1.6
00:11:41.418 [xUnit] [INFO] - [GoogleTest-1.6] - 1 test report file(s) were found with the pattern 'catkin_workspace/test_results/**/*.xml' relative to '/home/jenkins-slave/workspace/Idev__geometry_experimental__ubuntu_trusty_amd64' for the testing framework 'GoogleTest-1.6'.
00:11:41.420 [xUnit] [INFO] - Converting '/home/jenkins-slave/workspace/Idev__geometry_experimental__ubuntu_trusty_amd64/catkin_workspace/test_results/tf2_sensor_msgs/rostest-test_test.xml' .
00:11:41.480 [xUnit] [INFO] - Check 'Failed Tests' threshold.
00:11:41.480 [xUnit] [INFO] - Check 'Skipped Tests' threshold.
00:11:41.480 [xUnit] [INFO] - Setting the build status to SUCCESS
00:11:41.480 [xUnit] [INFO] - Stopping recording.
```

Looking at the workspace it's true that there is only one directory tf2_sensor_msgs with one xml file in it. 

It appears that this was the last test run and all the other results from other packages were cleared.

**Comment by dirk-thomas** [comment]
The build farm invokes `catkin_make_isolated` with a specific `CATKIN_TEST_RESULTS_DIR`. Since each package is build in isolation each one will clean the test results folder before running its own tests.

Since this should work on the command line too I moved the ticket to `catkin`: ros/catkin#737
