### ISSUE TITLE
custom rosdistro documentation

### ISSUE THREAD

**Issue by sevenbill** [ros-infrastructure/ros_buildfarm#802]
Can someone clarify [this](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/custom_rosdistro.rst#add-a-tag-to-custom-distribution-files)

I think the docs are suggesting to create a `melodic/local.yaml` in addition to `melodic/distribution.yaml` in the forked rosdistro and then add a tag to filter job creation in "build files in the ROS build farm configuration".

Looking at `distribution.yaml` the only existing `tags` are
```
      tags:
        release: release/melodic/{package}/{version}
```
Is there an example somewhere?

Which build files does this refer to?
```
This allows the build files in the ROS build farm configuration to operate
only on the packages / repositories from your custom distribution file.
```
`generate_all_jobs.py` didn't seem to have a way to pass a filter tag, am I misunderstanding something?

**Comment by dirk-thomas** [comment]
Please see the proposed improvement to the docs which:
* clarifies where the `tags` are being added as well as
* reference the section about whitelisting tags in build files.

**Comment by sevenbill** [comment]
Thanks Dirk!

I think that makes sense, let me check that I can get it working.

**Comment by sevenbill** [comment]
To confirm, I think I have things working. Well, at least the tag filtering bit
