### ISSUE TITLE
extend rosdistro audit to make sure there's consistency between release repos and rosdistro

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#820]
Similar to what https://github.com/ros2/ros2/issues/963 is doing.

**Comment by dirk-thomas** [comment]
@tfoote Can you clarify what the goal / acceptance criteria for this ticket is since this repo doesn't contain / store any branch information.

**Comment by tfoote** [comment]
The rosdistro _audit tool from #815 should run the analysis or a similar analysis as the script in the above tool to make sure that the rosdistro is consistent with the release repositories. 

@clalancette created a script to do this here: https://github.com/ros/rosdistro/pull/25908 which could be integrated into the audit.

**Comment by dirk-thomas** [comment]
@tfoote The description is still very fuzzy. From reading it I don't know what the goal / acceptance criteria of this ticket is. Please be more concrete, e.g. what exactly should be checked, where should that check happen, etc.

**Comment by dirk-thomas** [comment]
Closing for now to due no further response. Please feel free to comment with the requested information and the ticket can be reopened when the scope / acceptance criteria is clear.
