### ISSUE TITLE
Adding custom distribution name tries to source wrong setup.bash

### ISSUE THREAD

**Issue by dejanpan** [ros-infrastructure/ros_buildfarm#86]
We tried to add our own distro name (e.g. deepfield-indigo) in our forked version of https://github.com/ros/rosdistro/blob/master/index.yaml. 
However build scripts tried to then use /opt/ros/deepfield-indigo/setup.bash to source ROS environment. That folder/file does not exist.

**Comment by dirk-thomas** [comment]
The path to the setup file is determined based on the rosdistro name. In your case `deepfield-indigo`. As far as I can see the buildfarm has no way to determine that your packages are being installed to `/opt/ros/indigo` therefore I am leaning towards closing this with "wontfix". I would be curious though how you have worked around this in the meantime.

**Comment by dirk-thomas** [comment]
I will close this since I don't think there is anything the buildfarm can do about it.
