### ISSUE TITLE
Dev jobs fail with "java.lang.IllegalArgumentException: The tools section is required"

### ISSUE THREAD

**Issue by ipa-mdl** [ros-infrastructure/ros_buildfarm#871]
The ros_canopen dev jobs (ubuntu & debian) just started to fail ~~in~~after? the "Create collated test stats dir" section.

* https://build.ros.org/job/Mdev__ros_canopen__ubuntu_bionic_amd64/30/console
* https://build.ros.org/job/Ndev__ros_canopen__ubuntu_focal_amd64/10/console
* https://build.ros.org/job/Ndev_db__ros_canopen__debian_buster_amd64/10/console

> 12:52:26 ERROR: Build step failed with exception
> 12:52:27 java.lang.IllegalArgumentException: The tools section is required.
> 12:52:27 	at org.jenkinsci.plugins.xunit.XUnitProcessor.<init>(XUnitProcessor.java:141)
> 12:52:27 	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:185)
> 12:52:27 	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
> 12:52:27 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
> 12:52:27 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
> 12:52:27 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
> 12:52:27 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
> 12:52:27 	at hudson.model.Build$BuildExecution.post2(Build.java:177)
> 12:52:27 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:697)
> 12:52:27 	at hudson.model.Run.execute(Run.java:1932)
> 12:52:27 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
> 12:52:27 	at hudson.model.ResourceController.execute(ResourceController.java:97)
> 12:52:27 	at hudson.model.Executor.run(Executor.java:429)
> 12:52:27 Build step 'Publish xUnit test result report' marked build as failure

**Comment by gavanderhoorn** [comment]
It seems additions after the "collated test stats" feature did not add additional section headings.

The error:

> Build step 'Publish xUnit test result report' marked build as failure

seems to be coming from something else (ie: the `mkdir -p ...` is not failing).

**Comment by ipa-mdl** [comment]
And it looks like that has affected all normally succeeding ROS1 dev jobs for at least the last ~16h. (Last successful test job: ~17h ago)

**Comment by gavanderhoorn** [comment]
Seems related: [xunit 2.3.4 fails to read xunit 1.102 configs](https://issues.jenkins.io/browse/JENKINS-58222).

**Comment by clalancette** [comment]
A similar problem caused all of the overnight ROS 2 CI jobs to fail: https://ci.ros2.org/view/nightly/

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/upgrade-to-jenkins-2-277-3-causing-job-failures-across-ros-build-farms/20013/1

**Comment by nuclearsandwich** [comment]
I think the underlying problem is the XStream updates introduced in 2.277.3

> As described in the Spring and XStream updates (breaking changes!) blog post, this release updates and replaces outdated internal components. The Acegi security library used for authentication has been replaced by Spring Security (JEP-227). See the Spring Security compatibility table for the latest plugin compatibility status. A fork of the XStream library used to read and write XML files has been replaced by the upstream version of XStream (JEP-228). See the XStream compatibility table for the latest plugin compatibility status. 

When reading the above paragraph of the [changelog] initially I glossed passed the "breaking changes!" after seeing the "user interface components" discussion and missed the later xstream paragraph.

According to the [compatibility table](https://github.com/jenkinsci/jep/blob/master/jep/2f28/compatibility.adoc) xunit requires an upgrade to at least 2.4.0 to be compatible. In ros2/ci we were able to come up with a temporary workaround (https://github.com/ros2/ci/pull/569) which at least appears to be running but I'm hesitant to make the same change to ros_buildfarm due to the scale of reconfiguration required as well as considering whether or not the change is even necessary or forward compatible with xunit 2.4.0. I'm in the process of setting up a staging server with the plugin updates necessary to run xunit 2.4.0 to check how things work there.

**Comment by nuclearsandwich** [comment]
The above investigation bore out and I've opened a PR for the ros-buildfarm cookbook updating the xunit plugin to 2.4.0. I'd have to do more changelog scanning to assess how risky a full upgrade to 3.x is but https://github.com/ros-infrastructure/cookbook-ros-buildfarm/pull/89 should get us back to operational as long as it passes review.

**Comment by nuclearsandwich** [comment]
The above change has been deployed to build.ros2.org but was not able to resolve the issue in all cases.

**Comment by nuclearsandwich** [comment]
I fetched the XML configuration from both staging and production to compare them and found that although the creation of the devel job with the old configuration was accepted without error the affected configuration block was dropped entirely. It seems that there is no compatibility with the old config block and so I'll put an additional PR in to update the config and we'll reconfigure everything.

**Comment by nuclearsandwich** [comment]
One thing we still don't know is whether the future versions of xunit+jenkins will "prefer" the `types` vs `tools` for the name of this XML section. Deploying the updated plugins to ci.ros2.org which is not affected by https://github.com/ros-infrastructure/cookbook-ros-buildfarm/pull/90 will allow us to see what Jenkins re-serializes the xml as on save.
