### ISSUE TITLE
13 jobs still use EOL xenial base images

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#878]
Following #877 

## Already Failing
* [x] doc_independent #877 
* [ ] doc_rosindex
  * [x] https://github.com/ros2/ros2_documentation/pull/1518
  * [x] https://github.com/ros-infrastructure/rosindex/pull/268
  * [ ] https://github.com/hidmic/sphinx-tabs/pull/1

## Not yet failing
* [x] ci_create_reconfigure_task https://github.com/ros-infrastructure/ros_buildfarm/pull/906
* [x] devel_create_reconfigure_task https://github.com/ros-infrastructure/ros_buildfarm/pull/906
* [x] doc_create_reconfigure_task https://github.com/ros-infrastructure/ros_buildfarm/pull/884
* [x] doc_metadata_task https://github.com/ros-infrastructure/ros_buildfarm/pull/884
* [x] rosdistro_cache_task https://github.com/ros-infrastructure/ros_buildfarm/pull/886
* [x] release_check_sync_criteria_task https://github.com/ros-infrastructure/ros_buildfarm/pull/886
* [x] release_create_reconfigure_task https://github.com/ros-infrastructure/ros_buildfarm/pull/886
* [x] release_create_trigger_task https://github.com/ros-infrastructure/ros_buildfarm/pull/886
* [x] blocked_releases_page_task https://github.com/ros-infrastructure/ros_buildfarm/pull/885
* [x] blocked_source_entries_page_task https://github.com/ros-infrastructure/ros_buildfarm/pull/885
* [x] release_compare_page_task https://github.com/ros-infrastructure/ros_buildfarm/pull/885
* [x] release_status_page_task https://github.com/ros-infrastructure/ros_buildfarm/pull/885

**Comment by nuclearsandwich** [comment]
@tfoote Propose deprecation note hidmic/sphinx-tabs#1 is the only outstanding TODO on this issue.
Since the rosindex job is running (now no longer on Xenial) is that work still required before we can close this one out?

**Comment by tfoote** [comment]
Yeah we can close this out now. The sphinx-tabs us removed now: https://github.com/ros-infrastructure/rosindex/pull/268 so the  deprecation note is valuable but not necessary for our purposes now.
