### ISSUE TITLE
doc jobs fail on buildfarm

### ISSUE THREAD

**Issue by rhaschke** [ros-infrastructure/ros_buildfarm#893]
I'm not sure, this is the right place to report this issue. But recent doc build jobs on the ROS1 build farm are failing due to:
`org.jenkinsci.plugins.scriptsecurity.scripts.UnapprovedUsageException: script not yet approved for use`
For example:
- https://build.ros.org/view/Ndoc/job/Ndoc__class_loader__ubuntu_focal_amd64/
- https://build.ros.org/view/Ndoc/job/Ndoc__rviz__ubuntu_focal_amd64/

**Comment by gavanderhoorn** [comment]
I also got those emails: https://github.com/osrf/infrastructure/issues/4.

**Comment by rhaschke** [comment]
Closed in https://github.com/osrf/infrastructure/issues/4.
