### ISSUE TITLE
Documentation: note that external apt repositories used by buildfarm must have source packages enabled

### ISSUE THREAD

**Issue by jjekircp** [ros-infrastructure/ros_buildfarm#92]
Apologies for the slightly imprecise title. I tried building a private ROS package that depended on a system .deb package only available in one of my internal apt repositories.

I added that apt repository to the `<distribution>`/release-build.yaml file in the ros_buildfarm_config fork, then noticed that the apt-get update was failing during the binary job.

It turned out that I had to go into the reprepro configuration for my internal apt repository and add "source" to the list of architectures in the conf/distributions file.

I realised when I looked at templates/snippet/add_distribution_repositories.Dockerfile.em in the ros_buildfarm repository that the "deb-src" entry is always added, irrespective of whether or not the given apt repository is set up for source packages. 

I don't think anything is actually broken here, but it would be helpful to have a note on this in the documentation, particularly for buildbot_ros users who aren't expecting extra apt repositories to be added to the sources.list with a deb-src entry. 

For reference, this is the error message given by apt-get update in the binary job:
```
Unable to find expected entry 'main/source/Sources' in Release file
```

**Comment by tfoote** [comment]
There is an if statement in the template to turn off the deb-src entry. [here](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/snippet/add_distribution_repositories.Dockerfile.em#L7) 

Can you not set that to false for the repo?

**Comment by tfoote** [comment]
Looking a little deeper, we do have the flag and it's false in most cases except the binary builds. In the case of the binary builds it's on because that is where it gets the sourcedeb to build. Thus it's required. We should make sure to fix the reprepro configuration to make sure to add source as a config option by default.

**Comment by jjekircp** [comment]
I'm a bit confused as I don't see how changing reprepro configuration would resolve this issue, as it's the reprepro configuration of a repository completely outside of buildfarm that's the issue here.

The obvious solution I see is to change the documentation to ensure that all repositories listed in the build files are publishing source debs, then it's safe to write deb-src entries for each one.
The alternative would be only writing a the deb-src line for the repo machine, but that's a bit more complicated as, as far as I can tell, it's not obvious from that part of the code which URL corresponds to the buildfarm repo machine and which ones are external.

**Comment by dirk-thomas** [comment]
@jjekircp It has been a while since you created this issue but #322 addresses the problem now by only requiring source entries for the target repo since we never need them for any of the other repos.
