### ISSUE TITLE
ROS 1 wiki package changelogs are outdated or missing

### ISSUE THREAD

**Issue by peci1** [ros-infrastructure/ros_buildfarm#933]
The discussion of the problem started [on Discourse](https://discourse.ros.org/t/how-are-wiki-ros-org-changelogs-generated-and-why-are-they-so-out-of-date/23890) .

Two example packages with problems:

https://wiki.ros.org/message_filters points to [Changelog](http://docs.ros.org/en/noetic/changelogs/message_filters/changelog.html) for package message_filters, which has latest release 1.15.9. However, the latest entry in message_filters changelog on github is 1.15.14. 

https://wiki.ros.org/robot_body_filter - ROS Wiki is released into Noetic and has a doc job enabled. But the changelog is not there at all: [Changelog](http://docs.ros.org/en/noetic/changelogs/robot_body_filter/changelog.html) . However, the doc job log says it was processed and generated: [Ndoc__robot_body_filter__ubuntu_focal_amd64 #8 Console [Jenkins]](https://build.ros.org/view/Ndoc/job/Ndoc__robot_body_filter__ubuntu_focal_amd64/8/consoleFull#console-section-16)

Many many more packages are affected. I actually don't remember seeing a Changelog on Wiki that would be up-to-date (I've seen tens of them over the last few years).

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/how-are-wiki-ros-org-changelogs-generated-and-why-are-they-so-out-of-date/23890/7

**Comment by nuclearsandwich** [comment]
Two different Jenkins plugins handle propagating documentation information from doc jobs to the docs host.
The build file configuration was correctly pushing to docs.ros.org but the publish-over-ssh plugin's "docs" host was still set to the repository host, which is the default for a standalone build farm instance.

So this content has been publishing but to http://repositories.ros.org/docs instead of to docs.ros.org.

Fixing the configuration will require a config management update to the Jenkins host which I can schedule for next week.

**Comment by peci1** [comment]
Thanks!

**Comment by nuclearsandwich** [comment]
Complications in the deployment process have delayed the fix for this problem. I've got potential fixes that I'll be testing on our staging environment tomorrow but I can no longer commit to getting this change deployed this week.

**Comment by peci1** [comment]
As it's been broken for months, I think a few more weeks are not a big problem :)

**Comment by nuclearsandwich** [comment]
Changelog for robot_body_filter is live and, so far as I can tell, up to date: http://docs.ros.org/en/noetic/changelogs/robot_body_filter/changelog.html

@tfoote what, if anything, should be our procedure for backfilling documentation. Should I set up some scripts to kick off Mdoc and Ndoc jobs in batches?

**Comment by peci1** [comment]
Thanks!

**Comment by tfoote** [comment]
Unfortunately the changes aren't visible to the trigger mechanism. I'd suggest just triggering the doc jobs en-masse one a quiet evening and letting them run over night.  With `force=true`. Maybe melodic one night and noetic the second. THey're lower priority than the other jobs so will take a while but will get there.

**Comment by nuclearsandwich** [comment]
Force-triggered all Melodic jobs just now.

https://butt.holdings

https://build.ros.org/job/Mdoc_trigger-jobs/1/

**Comment by tfoote** [comment]
Things were quiet so I triggered all Ndoc jobs too: https://build.ros.org/job/Ndoc_trigger-jobs/1/

**Comment by tfoote** [comment]
We've run melodic and noetic with the fix. And a quick spot check seems to show them working so I'm going to close this.
