### ISSUE TITLE
Cmake version for ARM builds (Currently 3.10.2)

### ISSUE THREAD

**Issue by novatel-applications-engineering** [ros-infrastructure/ros_buildfarm#989]
Hello,

I am wondering if there is any plan to update the cmake version used on ARM builds? Is there a reason this specific version is used?

Thanks!

**Comment by cottsay** [comment]
The package versions available during buildfarm jobs should be the published versions for the corresponding target Linux distribution. For ROS Melodic, that should follow Ubuntu Bionic, which [currently publishes version 3.10.2](https://packages.ubuntu.com/bionic/cmake).

Is there another scenario where you're seeing CMake 3.10.2?

**Comment by novatel-applications-engineering** [comment]
Thanks for the information, that is what I wanted to know.
