### ISSUE TITLE
test results not being reported

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/ros_buildfarm#99]
http://54.183.26.131:8080/view/Idev/job/Idev__ros_comm__ubuntu_trusty_amd64/155/testReport/

**Comment by tfoote** [comment]
We do now have test results now. 
![test_trend](https://cloud.githubusercontent.com/assets/447804/11052206/e68fef26-870a-11e5-92b6-a90aeebd3602.png)
 http://54.183.26.131:8080/view/Idev/job/Idev__ros_comm__ubuntu_trusty_amd64/lastCompletedBuild/testReport/
