### ISSUE TITLE
Git config on Jenkins Build Server - Mdev Ubuntu Bionic

### ISSUE THREAD

**Issue by novatel-applications-engineering** [ros-infrastructure/ros_buildfarm#993]
Hello,

We are seeing an issue where the build is failing on the 'Mdev ubuntu Bionic" build from a Github configuration error. https://build.ros.org/view/Mdev/job/Mdev__novatel_oem7_driver__ubuntu_bionic_amd64/59/console

Is this something we can fix on our end or is it a setting on the build farm?
![image](https://user-images.githubusercontent.com/46907146/225692912-10cd4d17-0ac3-451c-a14d-98afd8332dce.png)

Thank you for your help.

**Comment by cottsay** [comment]
This is not a bug in `ros_buildfarm`, so this isn't an appropriate place to ask for help.

I believe that the [`novatel_edie`](https://github.com/novatel/novatel_edie/search?q=git) external project that [`novatel_oem7_driver`](https://github.com/novatel/novatel_oem7_driver/blob/7bfa77bf3906ef699d6717710a2ec9a70dd524b9/src/novatel_oem7_driver/CMakeLists.txt#L46) is pulling in has an environmental dependency that Git be not only installed, but configured for use.

You shouldn't rely on the user to have configured git. In either `novatel_edie` or `novatel_oem7_driver, you should set the appropriate environment variables to make Git use placeholder values for author and committer name and email: https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#_committing. Then it won't matter what the user's environment is like.

**Comment by gavanderhoorn** [comment]
Is `ExternalProject_Add(..)` supported on the buildfarm? It's used [here](https://github.com/novatel/novatel_oem7_driver/blob/1e71bad44d3f3fbcda8d0a61605badfd68a799b0/src/novatel_oem7_driver/CMakeLists.txt#L44-L51).

**Comment by cottsay** [comment]
> Is `ExternalProject_Add(..)` supported on the buildfarm?

That macro family works fine and doesn't require that git be configured like this. There is something else in the external project that seems to require committing in some way.

**Comment by gavanderhoorn** [comment]
>  There is something else in the external project that seems to require committing in some way.

I'm not sure; IIRC, you have to explicitly disable the update step for environments which don't let you / give you a configure(d) git.

**Comment by novatel-applications-engineering** [comment]
Thank you @cottsay and @gavanderhoorn, I appreciate the help. Suppressing that update fixed the issue. Sorry for posting this in the wrong place.
